"""
Django models for notifications app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""
import uuid
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField

try:
    from pgvector.django import VectorField
except ImportError:
    VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""
    organization = models.ForeignKey(
        'auth_core.Organizations',
        on_delete=models.CASCADE,
        related_name='%(class)ss'
    )

    class Meta:
        abstract = True



class NotificationLog(BaseModel):
    """Migrated from drizzle: clc-per-capita-schema.ts"""
    remittance_id = models.UUIDField(null=True, blank=True)
    organization_id = models.UUIDField()
    type = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'notification_log'
        verbose_name = 'NotificationLog'

class CommunicationPreferences(BaseModel):
    """Migrated from drizzle: communication-analytics-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'communication_preferences'
        verbose_name = 'CommunicationPreferences'

class MessageTemplates(BaseModel):
    """Migrated from drizzle: campaigns.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'message_templates'
        verbose_name = 'MessageTemplates'

class Campaigns(BaseModel):
    """Migrated from drizzle: campaigns.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'campaigns'
        verbose_name = 'Campaigns'

class MessageLog(BaseModel):
    """Migrated from drizzle: campaigns.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'message_log'
        verbose_name = 'MessageLog'

class CommunicationChannels(BaseModel):
    """Migrated from drizzle: campaigns.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'communication_channels'
        verbose_name = 'CommunicationChannels'

class MessageThreads(BaseModel):
    """Migrated from drizzle: messages.ts"""
    subject = models.TextField()
    member_id = models.TextField()
    staff_id = models.TextField(null=True, blank=True)
    organization_id = models.UUIDField()
    status = models.TextField(default='open')
    priority = models.TextField(null=True, blank=True, default='normal')
    category = models.TextField(null=True, blank=True)
    is_archived = models.BooleanField(default=False)
    last_message_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'message_threads'
        verbose_name = 'MessageThreads'
        ordering = ['-created_at']

class Messages(BaseModel):
    """Migrated from drizzle: messages.ts"""
    thread = models.ForeignKey('MessageThreads', on_delete=models.CASCADE, related_name='messages_thread_set')

    class Meta:
        db_table = 'messages'
        verbose_name = 'Messages'

class MessageReadReceipts(BaseModel):
    """Migrated from drizzle: messages.ts"""
    message = models.ForeignKey('Messages', on_delete=models.CASCADE, related_name='message_read_receipts_message_set')

    class Meta:
        db_table = 'message_read_receipts'
        verbose_name = 'MessageReadReceipts'

class MessageParticipants(BaseModel):
    """Migrated from drizzle: messages.ts"""
    thread = models.ForeignKey('MessageThreads', on_delete=models.CASCADE, related_name='message_participants_thread_set')

    class Meta:
        db_table = 'message_participants'
        verbose_name = 'MessageParticipants'

class MessageNotifications(BaseModel):
    """Migrated from drizzle: messages.ts"""
    user_id = models.TextField()
    message = models.ForeignKey('Messages', on_delete=models.CASCADE, related_name='message_notifications_message_set')

    class Meta:
        db_table = 'message_notifications'
        verbose_name = 'MessageNotifications'

class NewsletterTemplates(BaseModel):
    """Migrated from drizzle: newsletters.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'newsletter_templates'
        verbose_name = 'NewsletterTemplates'

class NewsletterDistributionLists(BaseModel):
    """Migrated from drizzle: newsletters.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'newsletter_distribution_lists'
        verbose_name = 'NewsletterDistributionLists'

class NewsletterListSubscribers(BaseModel):
    """Migrated from drizzle: newsletters.ts"""
    list_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'newsletter_list_subscribers'
        verbose_name = 'NewsletterListSubscribers'

class NewsletterCampaigns(BaseModel):
    """Migrated from drizzle: newsletters.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'newsletter_campaigns'
        verbose_name = 'NewsletterCampaigns'

class NewsletterRecipients(BaseModel):
    """Migrated from drizzle: newsletters.ts"""
    campaign_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'newsletter_recipients'
        verbose_name = 'NewsletterRecipients'

class NewsletterEngagement(BaseModel):
    """Migrated from drizzle: newsletters.ts"""
    campaign_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'newsletter_engagement'
        verbose_name = 'NewsletterEngagement'

class UserNotificationPreferences(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    user_id = models.TextField(unique=True)
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'user_notification_preferences'
        verbose_name = 'UserNotificationPreferences'

class NotificationTracking(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    organization_id = models.UUIDField()
    recipient_id = models.UUIDField(null=True, blank=True)
    type = models.TextField()
    status = models.TextField(default='pending')
    priority = models.TextField(default='normal')
    subject = models.TextField(null=True, blank=True)
    body = models.TextField()
    html_body = models.TextField(null=True, blank=True)
    template_id = models.TextField(null=True, blank=True)
    template_data = models.JSONField(default=dict, null=True, blank=True)
    provider_id = models.TextField(null=True, blank=True)
    external_message_id = models.TextField(null=True, blank=True)
    action_url = models.TextField(null=True, blank=True)
    action_label = models.TextField(null=True, blank=True)
    sent_at = models.DateTimeField(null=True, blank=True)
    delivered_at = models.DateTimeField(null=True, blank=True)
    failure_reason = models.TextField(null=True, blank=True)
    failure_count = models.IntegerField(null=True, blank=True, default=0)
    last_failure_at = models.DateTimeField(null=True, blank=True)
    metadata = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = 'notification_tracking'
        verbose_name = 'NotificationTracking'
        ordering = ['-created_at']

class InAppNotifications(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    user_id = models.TextField()
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'in_app_notifications'
        verbose_name = 'InAppNotifications'

class NotificationHistory(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    user_id = models.TextField(null=True, blank=True)
    organization = models.ForeignKey('auth_core.Organizations', on_delete=models.CASCADE, related_name='notification_history_organization_set', null=True, blank=True)

    class Meta:
        db_table = 'notification_history'
        verbose_name = 'NotificationHistory'

class Notifications(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'notifications'
        verbose_name = 'Notifications'

class NotificationTemplates(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'notification_templates'
        verbose_name = 'NotificationTemplates'

class NotificationQueue(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'notification_queue'
        verbose_name = 'NotificationQueue'

class NotificationDeliveryLog(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'notification_delivery_log'
        verbose_name = 'NotificationDeliveryLog'

class NotificationBounces(BaseModel):
    """Migrated from drizzle: notifications.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'notification_bounces'
        verbose_name = 'NotificationBounces'

class PushDevices(BaseModel):
    """Migrated from drizzle: push-notifications.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'push_devices'
        verbose_name = 'PushDevices'

class PushNotificationTemplates(BaseModel):
    """Migrated from drizzle: push-notifications.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'push_notification_templates'
        verbose_name = 'PushNotificationTemplates'

class PushNotifications(BaseModel):
    """Migrated from drizzle: push-notifications.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'push_notifications'
        verbose_name = 'PushNotifications'

class PushDeliveries(BaseModel):
    """Migrated from drizzle: push-notifications.ts"""
    notification_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'push_deliveries'
        verbose_name = 'PushDeliveries'

class SmsTemplates(BaseModel):
    """Migrated from drizzle: sms.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'sms_templates'
        verbose_name = 'SmsTemplates'

class SmsCampaigns(BaseModel):
    """Migrated from drizzle: sms.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'sms_campaigns'
        verbose_name = 'SmsCampaigns'

class SmsMessages(BaseModel):
    """Migrated from drizzle: sms.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'sms_messages'
        verbose_name = 'SmsMessages'

class SmsConversations(BaseModel):
    """Migrated from drizzle: sms.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'sms_conversations'
        verbose_name = 'SmsConversations'

class SmsCampaignRecipients(BaseModel):
    """Migrated from drizzle: sms.ts"""
    campaign_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'sms_campaign_recipients'
        verbose_name = 'SmsCampaignRecipients'

class SmsOptOuts(BaseModel):
    """Migrated from drizzle: sms.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'sms_opt_outs'
        verbose_name = 'SmsOptOuts'

class SmsRateLimits(BaseModel):
    """Migrated from drizzle: sms.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'sms_rate_limits'
        verbose_name = 'SmsRateLimits'

class MobileDevices(BaseModel):
    """Migrated from drizzle: mobile-devices-schema.ts"""
    device_token = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'mobile_devices'
        verbose_name = 'MobileDevices'

class MobileNotifications(BaseModel):
    """Migrated from drizzle: mobile-devices-schema.ts"""
    device = models.ForeignKey('MobileDevices', on_delete=models.CASCADE, related_name='mobile_notifications_device_set', null=True, blank=True)

    class Meta:
        db_table = 'mobile_notifications'
        verbose_name = 'MobileNotifications'

class MobileSyncQueue(BaseModel):
    """Migrated from drizzle: mobile-devices-schema.ts"""
    device = models.ForeignKey('MobileDevices', on_delete=models.CASCADE, related_name='mobile_sync_queue_device_set', null=True, blank=True)

    class Meta:
        db_table = 'mobile_sync_queue'
        verbose_name = 'MobileSyncQueue'

class MobileAnalytics(BaseModel):
    """Migrated from drizzle: mobile-devices-schema.ts"""
    session_id = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'mobile_analytics'
        verbose_name = 'MobileAnalytics'

class MobileAppConfig(BaseModel):
    """Migrated from drizzle: mobile-devices-schema.ts"""
    organization = models.ForeignKey('auth_core.Organizations', on_delete=models.CASCADE, related_name='mobile_app_config_organization_set', null=True, blank=True)

    class Meta:
        db_table = 'mobile_app_config'
        verbose_name = 'MobileAppConfig'

class CommunicationPreferencesPhase4(BaseModel):
    """Migrated from drizzle: phase-4-messaging-schema.ts"""
    user_id = models.TextField()
    organization_id = models.UUIDField()
    email_opt_in = models.TextField(null=True, blank=True, default='true')
    sms_opt_in = models.TextField(null=True, blank=True, default='true')
    quiet_hours_start = models.TextField(null=True, blank=True)
    quiet_hours_end = models.TextField(null=True, blank=True)
    timezone = models.TextField(null=True, blank=True, default='America/Toronto')

    class Meta:
        db_table = 'communication_preferences_phase4'
        verbose_name = 'CommunicationPreferencesPhase4'
        ordering = ['-created_at']
