"""
URL configuration for notifications app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'notification-log', views.NotificationLogViewSet)
router.register(r'communication-preferences', views.CommunicationPreferencesViewSet)
router.register(r'message-templates', views.MessageTemplatesViewSet)
router.register(r'campaigns', views.CampaignsViewSet)
router.register(r'message-log', views.MessageLogViewSet)
router.register(r'communication-channels', views.CommunicationChannelsViewSet)
router.register(r'message-threads', views.MessageThreadsViewSet)
router.register(r'messages', views.MessagesViewSet)
router.register(r'message-read-receipts', views.MessageReadReceiptsViewSet)
router.register(r'message-participants', views.MessageParticipantsViewSet)
router.register(r'message-notifications', views.MessageNotificationsViewSet)
router.register(r'newsletter-templates', views.NewsletterTemplatesViewSet)
router.register(r'newsletter-distribution-lists', views.NewsletterDistributionListsViewSet)
router.register(r'newsletter-list-subscribers', views.NewsletterListSubscribersViewSet)
router.register(r'newsletter-campaigns', views.NewsletterCampaignsViewSet)
router.register(r'newsletter-recipients', views.NewsletterRecipientsViewSet)
router.register(r'newsletter-engagement', views.NewsletterEngagementViewSet)
router.register(r'user-notification-preferences', views.UserNotificationPreferencesViewSet)
router.register(r'notification-tracking', views.NotificationTrackingViewSet)
router.register(r'in-app-notifications', views.InAppNotificationsViewSet)
router.register(r'notification-history', views.NotificationHistoryViewSet)
router.register(r'notifications', views.NotificationsViewSet)
router.register(r'notification-templates', views.NotificationTemplatesViewSet)
router.register(r'notification-queue', views.NotificationQueueViewSet)
router.register(r'notification-delivery-log', views.NotificationDeliveryLogViewSet)
router.register(r'notification-bounces', views.NotificationBouncesViewSet)
router.register(r'push-devices', views.PushDevicesViewSet)
router.register(r'push-notification-templates', views.PushNotificationTemplatesViewSet)
router.register(r'push-notifications', views.PushNotificationsViewSet)
router.register(r'push-deliveries', views.PushDeliveriesViewSet)
router.register(r'sms-templates', views.SmsTemplatesViewSet)
router.register(r'sms-campaigns', views.SmsCampaignsViewSet)
router.register(r'sms-messages', views.SmsMessagesViewSet)
router.register(r'sms-conversations', views.SmsConversationsViewSet)
router.register(r'sms-campaign-recipients', views.SmsCampaignRecipientsViewSet)
router.register(r'sms-opt-outs', views.SmsOptOutsViewSet)
router.register(r'sms-rate-limits', views.SmsRateLimitsViewSet)
router.register(r'mobile-devices', views.MobileDevicesViewSet)
router.register(r'mobile-notifications', views.MobileNotificationsViewSet)
router.register(r'mobile-sync-queue', views.MobileSyncQueueViewSet)
router.register(r'mobile-analytics', views.MobileAnalyticsViewSet)
router.register(r'mobile-app-config', views.MobileAppConfigViewSet)
router.register(r'communication-preferences-phase4', views.CommunicationPreferencesPhase4ViewSet)

app_name = 'notifications'

urlpatterns = [
    path('', include(router.urls)),
]