# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardPackets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "BoardPackets",
                "db_table": "board_packets",
            },
        ),
        migrations.CreateModel(
            name="BoardPacketTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "BoardPacketTemplates",
                "db_table": "board_packet_templates",
            },
        ),
        migrations.CreateModel(
            name="DataAggregationConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DataAggregationConsent",
                "db_table": "data_aggregation_consent",
            },
        ),
        migrations.CreateModel(
            name="DocumentFolders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DocumentFolders",
                "db_table": "document_folders",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Documents",
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentSigners",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DocumentSigners",
                "db_table": "document_signers",
            },
        ),
        migrations.CreateModel(
            name="ImpactMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ImpactMetrics",
                "db_table": "impact_metrics",
            },
        ),
        migrations.CreateModel(
            name="MemberDocuments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.TextField()),
                ("file_name", models.TextField()),
                ("file_url", models.TextField()),
                ("file_size", models.IntegerField()),
                ("file_type", models.TextField()),
                (
                    "category",
                    models.TextField(blank=True, default="General", null=True),
                ),
                ("uploaded_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "MemberDocuments",
                "db_table": "member_documents",
            },
        ),
        migrations.CreateModel(
            name="MovementTrends",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.TextField()),
                ("dimension", models.TextField()),
                ("aggregated_count", models.IntegerField()),
                ("organizations_contributing", models.IntegerField()),
                ("timeframe", models.TextField()),
                ("insights", models.TextField()),
                ("legislative_brief_relevance", models.BooleanField(default=False)),
                ("emerging_pattern", models.BooleanField(default=False)),
                ("confidence_level", models.TextField(default="medium")),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "MovementTrends",
                "db_table": "movement_trends",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizerImpacts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OrganizerImpacts",
                "db_table": "organizer_impacts",
            },
        ),
        migrations.CreateModel(
            name="PilotApplications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_name", models.TextField()),
                ("organization_type", models.TextField()),
                ("contact_name", models.TextField()),
                ("contact_email", models.TextField()),
                ("contact_phone", models.TextField(blank=True, null=True)),
                ("member_count", models.IntegerField()),
                ("jurisdictions", models.TextField()),
                ("sectors", models.TextField()),
                ("current_system", models.TextField(blank=True, null=True)),
                ("challenges", models.TextField()),
                ("goals", models.TextField()),
                (
                    "readiness_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "PilotApplications",
                "db_table": "pilot_applications",
            },
        ),
        migrations.CreateModel(
            name="PilotMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pilot_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PilotMetrics",
                "db_table": "pilot_metrics",
            },
        ),
        migrations.CreateModel(
            name="ShopifyConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ShopifyConfig",
                "db_table": "shopify_config",
            },
        ),
        migrations.CreateModel(
            name="SignatureAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workflow_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SignatureAuditLog",
                "db_table": "signature_audit_log",
            },
        ),
        migrations.CreateModel(
            name="SignatureAuditTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SignatureAuditTrail",
                "db_table": "signature_audit_trail",
            },
        ),
        migrations.CreateModel(
            name="SignatureDocuments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SignatureDocuments",
                "db_table": "signature_documents",
            },
        ),
        migrations.CreateModel(
            name="SignatureTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SignatureTemplates",
                "db_table": "signature_templates",
            },
        ),
        migrations.CreateModel(
            name="SignatureVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workflow_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SignatureVerification",
                "db_table": "signature_verification",
            },
        ),
        migrations.CreateModel(
            name="SignatureWorkflows",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SignatureWorkflows",
                "db_table": "signature_workflows",
            },
        ),
        migrations.CreateModel(
            name="Signers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workflow_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Signers",
                "db_table": "signers",
            },
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.TextField()),
                ("quote", models.TextField()),
                ("author", models.TextField()),
                ("role", models.TextField()),
                ("organization", models.TextField(blank=True, null=True)),
                ("organization_type", models.TextField(blank=True, null=True)),
                ("photo", models.TextField(blank=True, null=True)),
                ("featured", models.BooleanField(default=False)),
                ("visibility", models.TextField(default="public")),
                ("created_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Testimonials",
                "db_table": "testimonials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookReceipts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.TextField()),
                ("webhook_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "WebhookReceipts",
                "db_table": "webhook_receipts",
            },
        ),
        migrations.CreateModel(
            name="BoardPacketDistributions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_packet_distributions_packet_set",
                        to="content.boardpackets",
                    ),
                ),
            ],
            options={
                "verbose_name": "BoardPacketDistributions",
                "db_table": "board_packet_distributions",
            },
        ),
        migrations.CreateModel(
            name="BoardPacketSections",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_packet_sections_packet_set",
                        to="content.boardpackets",
                    ),
                ),
            ],
            options={
                "verbose_name": "BoardPacketSections",
                "db_table": "board_packet_sections",
            },
        ),
        migrations.CreateModel(
            name="CaseStudies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.TextField(unique=True)),
                ("title", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_studies_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "CaseStudies",
                "db_table": "case_studies",
            },
        ),
        migrations.CreateModel(
            name="CmsBlocks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_blocks_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "CmsBlocks",
                "db_table": "cms_blocks",
            },
        ),
        migrations.CreateModel(
            name="CmsMediaLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_media_library_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "CmsMediaLibrary",
                "db_table": "cms_media_library",
            },
        ),
        migrations.CreateModel(
            name="CmsNavigationMenus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_navigation_menus_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "CmsNavigationMenus",
                "db_table": "cms_navigation_menus",
            },
        ),
        migrations.CreateModel(
            name="CmsPages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_pages_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "CmsPages",
                "db_table": "cms_pages",
            },
        ),
        migrations.CreateModel(
            name="CmsTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_templates_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "CmsTemplates",
                "db_table": "cms_templates",
            },
        ),
        migrations.CreateModel(
            name="EventCheckIns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_check_ins_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "EventCheckIns",
                "db_table": "event_check_ins",
            },
        ),
        migrations.CreateModel(
            name="EventRegistrations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "EventRegistrations",
                "db_table": "event_registrations",
            },
        ),
        migrations.CreateModel(
            name="JobApplications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "JobApplications",
                "db_table": "job_applications",
            },
        ),
        migrations.CreateModel(
            name="JobPostings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "JobPostings",
                "db_table": "job_postings",
            },
        ),
        migrations.CreateModel(
            name="JobSaved",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_saved_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "JobSaved",
                "db_table": "job_saved",
            },
        ),
        migrations.CreateModel(
            name="PublicContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_content_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "PublicContent",
                "db_table": "public_content",
            },
        ),
        migrations.CreateModel(
            name="PublicEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_events_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "PublicEvents",
                "db_table": "public_events",
            },
        ),
        migrations.CreateModel(
            name="SignatureWebhooksLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.TextField()),
                ("event_type", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_webhooks_log_document_set",
                        to="content.signaturedocuments",
                    ),
                ),
            ],
            options={
                "verbose_name": "SignatureWebhooksLog",
                "db_table": "signature_webhooks_log",
            },
        ),
        migrations.CreateModel(
            name="SocialAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "SocialAccounts",
                "db_table": "social_accounts",
            },
        ),
        migrations.CreateModel(
            name="SocialAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_analytics_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "SocialAnalytics",
                "db_table": "social_analytics",
            },
        ),
        migrations.CreateModel(
            name="SocialCampaigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_campaigns_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "SocialCampaigns",
                "db_table": "social_campaigns",
            },
        ),
        migrations.CreateModel(
            name="SocialEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_engagement_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "SocialEngagement",
                "db_table": "social_engagement",
            },
        ),
        migrations.CreateModel(
            name="SocialFeeds",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_feeds_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "SocialFeeds",
                "db_table": "social_feeds",
            },
        ),
        migrations.CreateModel(
            name="SocialPosts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_posts_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "SocialPosts",
                "db_table": "social_posts",
            },
        ),
        migrations.CreateModel(
            name="WebsiteSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_settings_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebsiteSettings",
                "db_table": "website_settings",
            },
        ),
    ]
