# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountMappings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AccountMappings",
                "db_table": "account_mappings",
            },
        ),
        migrations.CreateModel(
            name="AutopaySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "AutopaySettings",
                "db_table": "autopay_settings",
            },
        ),
        migrations.CreateModel(
            name="BankAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "BankAccounts",
                "db_table": "bank_accounts",
            },
        ),
        migrations.CreateModel(
            name="BankOfCanadaRates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rate_date", models.DateTimeField()),
                ("currency", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "BankOfCanadaRates",
                "db_table": "bank_of_canada_rates",
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "BankReconciliation",
                "db_table": "bank_reconciliation",
            },
        ),
        migrations.CreateModel(
            name="BankReconciliations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "BankReconciliations",
                "db_table": "bank_reconciliations",
            },
        ),
        migrations.CreateModel(
            name="ChartOfAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ChartOfAccounts",
                "db_table": "chart_of_accounts",
            },
        ),
        migrations.CreateModel(
            name="ClcApiConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ClcApiConfig",
                "db_table": "clc_api_config",
            },
        ),
        migrations.CreateModel(
            name="ClcBargainingTrends",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sector", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ClcBargainingTrends",
                "db_table": "clc_bargaining_trends",
            },
        ),
        migrations.CreateModel(
            name="ClcChartOfAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ClcChartOfAccounts",
                "db_table": "clc_chart_of_accounts",
            },
        ),
        migrations.CreateModel(
            name="ClcOauthTokens",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ClcOauthTokens",
                "db_table": "clc_oauth_tokens",
            },
        ),
        migrations.CreateModel(
            name="ClcOrganizationSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                (
                    "affiliate_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ClcOrganizationSyncLog",
                "db_table": "clc_organization_sync_log",
            },
        ),
        migrations.CreateModel(
            name="ClcPerCapitaBenchmarks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ClcPerCapitaBenchmarks",
                "db_table": "clc_per_capita_benchmarks",
            },
        ),
        migrations.CreateModel(
            name="ClcRemittanceMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ClcRemittanceMapping",
                "db_table": "clc_remittance_mapping",
            },
        ),
        migrations.CreateModel(
            name="ClcSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ClcSyncLog",
                "db_table": "clc_sync_log",
            },
        ),
        migrations.CreateModel(
            name="ClcUnionDensity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sector", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ClcUnionDensity",
                "db_table": "clc_union_density",
            },
        ),
        migrations.CreateModel(
            name="ClcWebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("webhook_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ClcWebhookLog",
                "db_table": "clc_webhook_log",
            },
        ),
        migrations.CreateModel(
            name="CostCenters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CostCenters",
                "db_table": "cost_centers",
            },
        ),
        migrations.CreateModel(
            name="CpiAdjustedPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_id", models.UUIDField()),
                ("item_description", models.TextField()),
                ("contract_id", models.UUIDField(blank=True, null=True)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "CpiAdjustedPricing",
                "db_table": "cpi_adjusted_pricing",
            },
        ),
        migrations.CreateModel(
            name="CpiData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CpiData",
                "db_table": "cpi_data",
            },
        ),
        migrations.CreateModel(
            name="CrossBorderTransactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateTimeField()),
                ("amount_cents", models.IntegerField()),
                (
                    "original_currency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CrossBorderTransactions",
                "db_table": "cross_border_transactions",
            },
        ),
        migrations.CreateModel(
            name="CurrencyEnforcementAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CurrencyEnforcementAudit",
                "db_table": "currency_enforcement_audit",
            },
        ),
        migrations.CreateModel(
            name="CurrencyEnforcementPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enforcement_enabled", models.BooleanField(default=False)),
                (
                    "mandatory_currency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CurrencyEnforcementPolicy",
                "db_table": "currency_enforcement_policy",
            },
        ),
        migrations.CreateModel(
            name="CurrencyEnforcementViolations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "violation_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CurrencyEnforcementViolations",
                "db_table": "currency_enforcement_violations",
            },
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CurrencyExchangeRates",
                "db_table": "currency_exchange_rates",
            },
        ),
        migrations.CreateModel(
            name="DuesRates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("local_id", models.UUIDField(blank=True, null=True)),
                ("unit_id", models.UUIDField(blank=True, null=True)),
                ("rate_name", models.TextField()),
                ("rate_type", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "DuesRates",
                "db_table": "dues_rates",
            },
        ),
        migrations.CreateModel(
            name="DuesTransactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("member_id", models.UUIDField()),
                ("assignment_id", models.UUIDField(blank=True, null=True)),
                ("rule_id", models.UUIDField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("charge", "Charge"),
                            ("payment", "Payment"),
                            ("adjustment", "Adjustment"),
                            ("refund", "Refund"),
                            ("waiver", "Waiver"),
                            ("late_fee", "Late Fee"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "DuesTransactions",
                "db_table": "dues_transactions",
            },
        ),
        migrations.CreateModel(
            name="EmployerRemittances",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employer_id", models.UUIDField()),
                ("organization_id", models.UUIDField()),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("fiscal_year", models.IntegerField()),
                ("fiscal_month", models.IntegerField()),
                ("remittance_date", models.DateTimeField()),
                ("remittance_number", models.TextField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "EmployerRemittances",
                "db_table": "employer_remittances",
            },
        ),
        migrations.CreateModel(
            name="ErpConnectors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ErpConnectors",
                "db_table": "erp_connectors",
            },
        ),
        migrations.CreateModel(
            name="ErpInvoices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ErpInvoices",
                "db_table": "erp_invoices",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_currency",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ExchangeRates",
                "db_table": "exchange_rates",
            },
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "FinancialAuditLog",
                "db_table": "financial_audit_log",
            },
        ),
        migrations.CreateModel(
            name="FinancialPeriods",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("local_id", models.UUIDField(blank=True, null=True)),
                ("fiscal_year", models.IntegerField()),
                ("fiscal_month", models.IntegerField()),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("status", models.TextField(default="open")),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.TextField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.TextField(blank=True, null=True)),
                (
                    "total_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "FinancialPeriods",
                "db_table": "financial_periods",
            },
        ),
        migrations.CreateModel(
            name="FmvAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "FmvAuditLog",
                "db_table": "fmv_audit_log",
            },
        ),
        migrations.CreateModel(
            name="FmvBenchmarks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "FmvBenchmarks",
                "db_table": "fmv_benchmarks",
            },
        ),
        migrations.CreateModel(
            name="FmvPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_enabled", models.BooleanField(default=False)),
                ("fmv_verification_required", models.BooleanField(default=False)),
                (
                    "competitive_bidding_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "FmvPolicy",
                "db_table": "fmv_policy",
            },
        ),
        migrations.CreateModel(
            name="FmvViolations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "violation_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "FmvViolations",
                "db_table": "fmv_violations",
            },
        ),
        migrations.CreateModel(
            name="FxRateAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "FxRateAuditLog",
                "db_table": "fx_rate_audit_log",
            },
        ),
        migrations.CreateModel(
            name="GlAccountMappings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "GlAccountMappings",
                "db_table": "gl_account_mappings",
            },
        ),
        migrations.CreateModel(
            name="GlTransactionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "GlTransactionLog",
                "db_table": "gl_transaction_log",
            },
        ),
        migrations.CreateModel(
            name="GlTrialBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "GlTrialBalance",
                "db_table": "gl_trial_balance",
            },
        ),
        migrations.CreateModel(
            name="IndependentAppraisals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "IndependentAppraisals",
                "db_table": "independent_appraisals",
            },
        ),
        migrations.CreateModel(
            name="JournalEntries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "JournalEntries",
                "db_table": "journal_entries",
            },
        ),
        migrations.CreateModel(
            name="MemberArrears",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(unique=True)),
                ("organization_id", models.UUIDField()),
                (
                    "total_owed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "MemberArrears",
                "db_table": "member_arrears",
            },
        ),
        migrations.CreateModel(
            name="MemberDuesLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField()),
                ("organization_id", models.UUIDField()),
                ("transaction_type", models.TextField()),
                ("transaction_date", models.DateTimeField()),
                ("effective_date", models.DateTimeField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "MemberDuesLedger",
                "db_table": "member_dues_ledger",
            },
        ),
        migrations.CreateModel(
            name="OrganizationBillingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OrganizationBillingConfig",
                "db_table": "organization_billing_config",
            },
        ),
        migrations.CreateModel(
            name="OrganizationContacts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "OrganizationContacts",
                "db_table": "organization_contacts",
            },
        ),
        migrations.CreateModel(
            name="PaymentClassificationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_name", models.TextField()),
                ("policy_description", models.TextField(blank=True, null=True)),
                ("effective_date", models.DateTimeField()),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("enforce_strict_separation", models.BooleanField(default=False)),
                ("allow_operational_fallback", models.BooleanField(default=False)),
                ("require_trust_account", models.BooleanField(default=False)),
                ("automatic_classification", models.BooleanField(default=False)),
                ("approved_by", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "PaymentClassificationPolicy",
                "db_table": "payment_classification_policy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentCycles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PaymentCycles",
                "db_table": "payment_cycles",
            },
        ),
        migrations.CreateModel(
            name="PaymentDisputes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PaymentDisputes",
                "db_table": "payment_disputes",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethods",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PaymentMethods",
                "db_table": "payment_methods",
            },
        ),
        migrations.CreateModel(
            name="PaymentPlans",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField()),
                ("organization_id", models.UUIDField()),
                ("plan_name", models.TextField()),
                (
                    "total_owed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "PaymentPlans",
                "db_table": "payment_plans",
            },
        ),
        migrations.CreateModel(
            name="PaymentRoutingRules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_type", models.TextField()),
                ("payment_category", models.TextField()),
                ("destination_account_type", models.TextField()),
                ("routing_mandatory", models.BooleanField(default=False)),
                ("allow_fallback", models.BooleanField(default=False)),
                ("routing_priority", models.TextField(default="1")),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "PaymentRoutingRules",
                "db_table": "payment_routing_rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payments",
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="PerCapitaRemittances",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("from_organization_id", models.UUIDField()),
                ("to_organization_id", models.UUIDField()),
                ("remittance_month", models.IntegerField()),
                ("remittance_year", models.IntegerField()),
                ("due_date", models.DateField()),
                ("total_members", models.IntegerField()),
                ("good_standing_members", models.IntegerField()),
                ("remittable_members", models.IntegerField()),
                (
                    "per_capita_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "PerCapitaRemittances",
                "db_table": "per_capita_remittances",
            },
        ),
        migrations.CreateModel(
            name="ProcurementBids",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("procurement_request_id", models.UUIDField()),
                ("bidder_name", models.TextField()),
                ("bidder_contact", models.TextField()),
                (
                    "bidder_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ProcurementBids",
                "db_table": "procurement_bids",
            },
        ),
        migrations.CreateModel(
            name="ProcurementRequests",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ProcurementRequests",
                "db_table": "procurement_requests",
            },
        ),
        migrations.CreateModel(
            name="RemittanceApprovals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remittance_id", models.UUIDField()),
                (
                    "approver_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "RemittanceApprovals",
                "db_table": "remittance_approvals",
            },
        ),
        migrations.CreateModel(
            name="RemittanceExceptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remittance_id", models.UUIDField()),
                ("line_item_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField()),
                ("exception_type", models.TextField()),
                ("severity", models.TextField(default="medium")),
                ("employee_number", models.TextField(blank=True, null=True)),
                ("employee_name", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "RemittanceExceptions",
                "db_table": "remittance_exceptions",
            },
        ),
        migrations.CreateModel(
            name="RemittanceLineItems",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remittance_id", models.UUIDField()),
                ("organization_id", models.UUIDField()),
                ("employee_number", models.TextField(blank=True, null=True)),
                ("employee_name", models.TextField(blank=True, null=True)),
                ("employment_type", models.TextField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("match_confidence", models.IntegerField(blank=True, null=True)),
                ("match_method", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "RemittanceLineItems",
                "db_table": "remittance_line_items",
            },
        ),
        migrations.CreateModel(
            name="Rl1TaxSlips",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Rl1TaxSlips",
                "db_table": "rl1_tax_slips",
            },
        ),
        migrations.CreateModel(
            name="StrikeFundDisbursements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "StrikeFundDisbursements",
                "db_table": "strike_fund_disbursements",
            },
        ),
        migrations.CreateModel(
            name="StrikeFundPaymentAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_date", models.DateTimeField()),
                ("audit_period", models.TextField()),
                ("total_strike_payments", models.TextField()),
                ("total_strike_amount", models.TextField()),
                ("strike_payments_to_correct_account", models.TextField()),
                ("strike_payments_to_wrong_account", models.TextField()),
                ("total_operational_payments", models.TextField()),
                ("total_operational_amount", models.TextField()),
                ("separation_compliance_rate", models.TextField()),
                ("total_violations", models.TextField()),
                ("critical_violations", models.TextField()),
                ("amount_misrouted", models.TextField(blank=True, null=True)),
                ("recommended_actions", models.TextField(blank=True, null=True)),
                ("audited_by", models.TextField()),
                ("audit_report", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "StrikeFundPaymentAudit",
                "db_table": "strike_fund_payment_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeConnectAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_type", models.TextField()),
                ("account_purpose", models.TextField()),
                ("stripe_account_id", models.TextField(unique=True)),
                ("account_status", models.TextField(default="active")),
                ("account_email", models.TextField()),
                ("account_name", models.TextField()),
                ("country", models.TextField(default="CA")),
                ("currency", models.TextField(default="CAD")),
                ("separate_account", models.BooleanField(default=False)),
                ("trust_account_designation", models.BooleanField(default=False)),
                ("bank_account_last4", models.TextField(blank=True, null=True)),
                ("bank_name", models.TextField(blank=True, null=True)),
                ("account_verified", models.BooleanField(default=False)),
                ("created_by", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "StripeConnectAccounts",
                "db_table": "stripe_connect_accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "StripeWebhookEvents",
                "db_table": "stripe_webhook_events",
            },
        ),
        migrations.CreateModel(
            name="SyncJobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SyncJobs",
                "db_table": "sync_jobs",
            },
        ),
        migrations.CreateModel(
            name="T106FilingTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fiscal_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "T106FilingTracking",
                "db_table": "t106_filing_tracking",
            },
        ),
        migrations.CreateModel(
            name="T4aTaxSlips",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "T4aTaxSlips",
                "db_table": "t4a_tax_slips",
            },
        ),
        migrations.CreateModel(
            name="TaxYearEndProcessing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tax_year", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "TaxYearEndProcessing",
                "db_table": "tax_year_end_processing",
            },
        ),
        migrations.CreateModel(
            name="TransactionCurrencyConversions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.UUIDField(unique=True)),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "TransactionCurrencyConversions",
                "db_table": "transaction_currency_conversions",
            },
        ),
        migrations.CreateModel(
            name="TransferPricingDocumentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.UUIDField()),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "TransferPricingDocumentation",
                "db_table": "transfer_pricing_documentation",
            },
        ),
        migrations.CreateModel(
            name="WeeklyThresholdTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "WeeklyThresholdTracking",
                "db_table": "weekly_threshold_tracking",
            },
        ),
        migrations.CreateModel(
            name="BankTransactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions_bank_account_set",
                        to="billing.bankaccounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "BankTransactions",
                "db_table": "bank_transactions",
            },
        ),
        migrations.CreateModel(
            name="DonationCampaigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_campaigns_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "DonationCampaigns",
                "db_table": "donation_campaigns",
            },
        ),
        migrations.CreateModel(
            name="DonationReceipts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_receipts_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "DonationReceipts",
                "db_table": "donation_receipts",
            },
        ),
        migrations.CreateModel(
            name="Donations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donations",
                "db_table": "donations",
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLines",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entry_lines_entry_set",
                        to="billing.journalentries",
                    ),
                ),
            ],
            options={
                "verbose_name": "JournalEntryLines",
                "db_table": "journal_entry_lines",
            },
        ),
        migrations.CreateModel(
            name="SeparatedPaymentTransactions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateTimeField()),
                ("payment_type", models.TextField()),
                ("payment_category", models.TextField()),
                ("payment_amount", models.TextField()),
                ("payment_currency", models.TextField(default="CAD")),
                ("payer_id", models.TextField()),
                ("payer_email", models.TextField()),
                ("payee_id", models.TextField(blank=True, null=True)),
                ("payee_name", models.TextField(blank=True, null=True)),
                ("stripe_payment_intent_id", models.TextField(blank=True, null=True)),
                ("stripe_charge_id", models.TextField(blank=True, null=True)),
                ("routed_to_account_type", models.TextField()),
                ("separation_enforced", models.BooleanField(default=False)),
                ("correct_account_used", models.BooleanField(default=False)),
                ("payment_status", models.TextField(default="pending")),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "routing_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="separated_payment_transactions_routing_rule_set",
                        to="billing.paymentroutingrules",
                    ),
                ),
                (
                    "routed_to_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="separated_payment_transactions_routed_to_account_set",
                        to="billing.stripeconnectaccounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "SeparatedPaymentTransactions",
                "db_table": "separated_payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="paymentroutingrules",
            name="destination_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_routing_rules_destination_account_set",
                to="billing.stripeconnectaccounts",
            ),
        ),
        migrations.AddField(
            model_name="paymentroutingrules",
            name="fallback_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_routing_rules_fallback_account_set",
                to="billing.stripeconnectaccounts",
            ),
        ),
        migrations.CreateModel(
            name="AccountBalanceReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reconciliation_date", models.DateTimeField()),
                ("account_type", models.TextField()),
                ("stripe_reported_balance", models.TextField()),
                ("system_calculated_balance", models.TextField()),
                ("balance_match", models.BooleanField(default=False)),
                ("discrepancy_amount", models.TextField(blank=True, null=True)),
                ("discrepancy_reason", models.TextField(blank=True, null=True)),
                ("reconciliation_status", models.TextField(default="pending")),
                ("reconciled_by", models.TextField(blank=True, null=True)),
                ("reconciliation_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_balance_reconciliation_account_set",
                        to="billing.stripeconnectaccounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "AccountBalanceReconciliation",
                "db_table": "account_balance_reconciliation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhiplashPreventionAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_date", models.DateTimeField()),
                ("action_type", models.TextField()),
                ("action_description", models.TextField()),
                ("performed_by", models.TextField()),
                ("compliance_impact", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiplash_prevention_audit_account_set",
                        to="billing.stripeconnectaccounts",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiplash_prevention_audit_transaction_set",
                        to="billing.separatedpaymenttransactions",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhiplashPreventionAudit",
                "db_table": "whiplash_prevention_audit",
            },
        ),
        migrations.CreateModel(
            name="WhiplashViolations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("violation_date", models.DateTimeField()),
                ("violation_type", models.TextField()),
                ("severity", models.TextField()),
                ("payment_type", models.TextField()),
                ("violation_description", models.TextField()),
                ("amount_involved", models.TextField(blank=True, null=True)),
                ("correction_required", models.BooleanField(default=False)),
                ("correction_action", models.TextField(blank=True, null=True)),
                ("violation_status", models.TextField(default="open")),
                ("detected_by", models.TextField(blank=True, null=True)),
                ("resolved_by", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "actual_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiplash_violations_actual_account_set",
                        to="billing.stripeconnectaccounts",
                    ),
                ),
                (
                    "expected_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiplash_violations_expected_account_set",
                        to="billing.stripeconnectaccounts",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiplash_violations_transaction_set",
                        to="billing.separatedpaymenttransactions",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhiplashViolations",
                "db_table": "whiplash_violations",
                "ordering": ["-created_at"],
            },
        ),
    ]
