"""
Django models for bargaining app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""
import uuid
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField

try:
    from pgvector.django import VectorField
except ImportError:
    VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""
    organization = models.ForeignKey(
        'auth_core.Organizations',
        on_delete=models.CASCADE,
        related_name='%(class)ss'
    )

    class Meta:
        abstract = True



class ArbitrationPrecedents(BaseModel):
    """Migrated from drizzle: arbitration-precedents-schema.ts"""
    source_organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'arbitration_precedents'
        verbose_name = 'ArbitrationPrecedents'

class PrecedentTags(BaseModel):
    """Migrated from drizzle: arbitration-precedents-schema.ts"""
    precedent_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'precedent_tags'
        verbose_name = 'PrecedentTags'

class PrecedentCitations(BaseModel):
    """Migrated from drizzle: arbitration-precedents-schema.ts"""
    precedent_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'precedent_citations'
        verbose_name = 'PrecedentCitations'

class Negotiations(BaseModel):
    """Migrated from drizzle: bargaining-negotiations-schema.ts"""
    organization_id = models.UUIDField()
    expiring_cba = models.ForeignKey('CollectiveAgreements', on_delete=models.CASCADE, related_name='negotiations_expiring_cba_set', null=True, blank=True)

    class Meta:
        db_table = 'negotiations'
        verbose_name = 'Negotiations'

class BargainingProposals(BaseModel):
    """Migrated from drizzle: bargaining-negotiations-schema.ts"""
    negotiation = models.ForeignKey('Negotiations', on_delete=models.CASCADE, related_name='bargaining_proposals_negotiation_set')

    class Meta:
        db_table = 'bargaining_proposals'
        verbose_name = 'BargainingProposals'

class TentativeAgreements(BaseModel):
    """Migrated from drizzle: bargaining-negotiations-schema.ts"""
    negotiation = models.ForeignKey('Negotiations', on_delete=models.CASCADE, related_name='tentative_agreements_negotiation_set')

    class Meta:
        db_table = 'tentative_agreements'
        verbose_name = 'TentativeAgreements'

class NegotiationSessions(BaseModel):
    """Migrated from drizzle: bargaining-negotiations-schema.ts"""
    negotiation = models.ForeignKey('Negotiations', on_delete=models.CASCADE, related_name='negotiation_sessions_negotiation_set')

    class Meta:
        db_table = 'negotiation_sessions'
        verbose_name = 'NegotiationSessions'

class BargainingTeamMembers(BaseModel):
    """Migrated from drizzle: bargaining-negotiations-schema.ts"""
    negotiation = models.ForeignKey('Negotiations', on_delete=models.CASCADE, related_name='bargaining_team_members_negotiation_set')

    class Meta:
        db_table = 'bargaining_team_members'
        verbose_name = 'BargainingTeamMembers'

class CbaClauses(BaseModel):
    """Migrated from drizzle: cba-clauses-schema.ts"""
    organization_id = models.UUIDField()
    cba = models.ForeignKey('CollectiveAgreements', on_delete=models.CASCADE, related_name='cba_clauses_cba_set')

    class Meta:
        db_table = 'cba_clauses'
        verbose_name = 'CbaClauses'

class ClauseComparisons(BaseModel):
    """Migrated from drizzle: cba-clauses-schema.ts"""
    comparison_name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'clause_comparisons'
        verbose_name = 'ClauseComparisons'

class WageProgressions(BaseModel):
    """Migrated from drizzle: cba-clauses-schema.ts"""
    cba = models.ForeignKey('CollectiveAgreements', on_delete=models.CASCADE, related_name='wage_progressions_cba_set')

    class Meta:
        db_table = 'wage_progressions'
        verbose_name = 'WageProgressions'

class BenefitComparisons(BaseModel):
    """Migrated from drizzle: cba-clauses-schema.ts"""
    cba = models.ForeignKey('CollectiveAgreements', on_delete=models.CASCADE, related_name='benefit_comparisons_cba_set')

    class Meta:
        db_table = 'benefit_comparisons'
        verbose_name = 'BenefitComparisons'

class ArbitrationDecisions(BaseModel):
    """Migrated from drizzle: cba-intelligence-schema.ts"""
    case_number = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'arbitration_decisions'
        verbose_name = 'ArbitrationDecisions'

class ArbitratorProfiles(BaseModel):
    """Migrated from drizzle: cba-intelligence-schema.ts"""
    name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'arbitrator_profiles'
        verbose_name = 'ArbitratorProfiles'

    def __str__(self):
        return str(self.name)

class BargainingNotes(BaseModel):
    """Migrated from drizzle: cba-intelligence-schema.ts"""
    cba = models.ForeignKey('CollectiveAgreements', on_delete=models.CASCADE, related_name='bargaining_notes_cba_set', null=True, blank=True)

    class Meta:
        db_table = 'bargaining_notes'
        verbose_name = 'BargainingNotes'

class CbaFootnotes(BaseModel):
    """Migrated from drizzle: cba-intelligence-schema.ts"""
    source_clause = models.ForeignKey('CbaClauses', on_delete=models.CASCADE, related_name='cba_footnotes_source_clause_set')

    class Meta:
        db_table = 'cba_footnotes'
        verbose_name = 'CbaFootnotes'

class CollectiveAgreements(BaseModel):
    """Migrated from drizzle: collective-agreements-schema.ts"""
    organization_id = models.UUIDField()
    cba_number = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'collective_agreements'
        verbose_name = 'CollectiveAgreements'

    def __str__(self):
        return str(self.cba_number)

class CbaVersionHistory(BaseModel):
    """Migrated from drizzle: collective-agreements-schema.ts"""
    cba = models.ForeignKey('CollectiveAgreements', on_delete=models.CASCADE, related_name='cba_version_history_cba_set')

    class Meta:
        db_table = 'cba_version_history'
        verbose_name = 'CbaVersionHistory'

class CbaContacts(BaseModel):
    """Migrated from drizzle: collective-agreements-schema.ts"""
    cba = models.ForeignKey('CollectiveAgreements', on_delete=models.CASCADE, related_name='cba_contacts_cba_set')

    class Meta:
        db_table = 'cba_contacts'
        verbose_name = 'CbaContacts'

class SharedClauseLibrary(BaseModel):
    """Migrated from drizzle: shared-library.ts"""
    source_organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'shared_clause_library'
        verbose_name = 'SharedClauseLibrary'

class ClauseLibraryTags(BaseModel):
    """Migrated from drizzle: shared-library.ts"""
    clause_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'clause_library_tags'
        verbose_name = 'ClauseLibraryTags'

class ClauseComparisonsHistory(BaseModel):
    """Migrated from drizzle: shared-library.ts"""
    user_id = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'clause_comparisons_history'
        verbose_name = 'ClauseComparisonsHistory'
