# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsScheduledReports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AnalyticsScheduledReports",
                "db_table": "analytics_scheduled_reports",
            },
        ),
        migrations.CreateModel(
            name="BenchmarkCategories",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_name", models.TextField(unique=True)),
                ("display_name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("category_group", models.TextField()),
                ("unit_type", models.TextField()),
                ("calculation_method", models.TextField(blank=True, null=True)),
                ("higher_is_better", models.BooleanField(default=False)),
                (
                    "display_order",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("icon", models.TextField(blank=True, null=True)),
                ("color", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "BenchmarkCategories",
                "db_table": "benchmark_categories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BenchmarkData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("benchmark_category_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "BenchmarkData",
                "db_table": "benchmark_data",
            },
        ),
        migrations.CreateModel(
            name="CommunicationAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CommunicationAnalytics",
                "db_table": "communication_analytics",
            },
        ),
        migrations.CreateModel(
            name="ContributionRates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rate_type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ContributionRates",
                "db_table": "contribution_rates",
            },
        ),
        migrations.CreateModel(
            name="CostOfLivingData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geography_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CostOfLivingData",
                "db_table": "cost_of_living_data",
            },
        ),
        migrations.CreateModel(
            name="ExternalDataSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ExternalDataSyncLog",
                "db_table": "external_data_sync_log",
            },
        ),
        migrations.CreateModel(
            name="OrganizationBenchmarkSnapshots",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OrganizationBenchmarkSnapshots",
                "db_table": "organization_benchmark_snapshots",
            },
        ),
        migrations.CreateModel(
            name="ReportDeliveryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ReportDeliveryHistory",
                "db_table": "report_delivery_history",
            },
        ),
        migrations.CreateModel(
            name="ReportExecutions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ReportExecutions",
                "db_table": "report_executions",
            },
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Reports",
                "db_table": "reports",
            },
        ),
        migrations.CreateModel(
            name="ReportShares",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ReportShares",
                "db_table": "report_shares",
            },
        ),
        migrations.CreateModel(
            name="ScheduledReports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ScheduledReports",
                "db_table": "scheduled_reports",
            },
        ),
        migrations.CreateModel(
            name="UnionDensity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geography_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "UnionDensity",
                "db_table": "union_density",
            },
        ),
        migrations.CreateModel(
            name="UserEngagementScores",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UserEngagementScores",
                "db_table": "user_engagement_scores",
            },
        ),
        migrations.CreateModel(
            name="WageBenchmarks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("noc_code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "WageBenchmarks",
                "db_table": "wage_benchmarks",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_metrics_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "AnalyticsMetrics",
                "db_table": "analytics_metrics",
            },
        ),
        migrations.CreateModel(
            name="ComparativeAnalyses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparative_analyses_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "ComparativeAnalyses",
                "db_table": "comparative_analyses",
            },
        ),
        migrations.CreateModel(
            name="InsightRecommendations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_recommendations_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "InsightRecommendations",
                "db_table": "insight_recommendations",
            },
        ),
        migrations.CreateModel(
            name="KpiConfigurations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_configurations_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "KpiConfigurations",
                "db_table": "kpi_configurations",
            },
        ),
        migrations.CreateModel(
            name="PageAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_analytics_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "PageAnalytics",
                "db_table": "page_analytics",
            },
        ),
        migrations.CreateModel(
            name="ReportTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "ReportTemplates",
                "db_table": "report_templates",
            },
        ),
        migrations.CreateModel(
            name="TrendAnalyses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend_analyses_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "TrendAnalyses",
                "db_table": "trend_analyses",
            },
        ),
    ]
