# Generated by Django 5.1.15 on 2026-03-04 06:05

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplianceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField(db_index=True)),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("on_demand", "On-Demand"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "snapshot_payload",
                    models.JSONField(
                        help_text="Full compliance state at time of capture"
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        help_text="SHA-256 of (snapshot_payload + previous_hash)",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of the preceding snapshot (empty for first)",
                        max_length=64,
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Monotonic sequence within org"
                    ),
                ),
                ("created_by", models.CharField(default="system", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["org_id", "snapshot_type"], name="idx_compsnap_org_type"
                    ),
                    models.Index(
                        fields=["org_id", "created_at"], name="idx_compsnap_org_time"
                    ),
                    models.Index(
                        fields=["org_id", "sequence_number"],
                        name="idx_compsnap_org_seq",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "sequence_number"), name="uq_compsnap_org_seq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("case_created", "Case Created"),
                            ("case_updated", "Case Updated"),
                            ("case_assigned", "Case Assigned"),
                            ("case_escalated", "Case Escalated"),
                            ("case_resolved", "Case Resolved"),
                            ("case_closed", "Case Closed"),
                            ("case_reopened", "Case Reopened"),
                            ("member_created", "Member Created"),
                            ("member_updated", "Member Updated"),
                            ("member_deactivated", "Member Deactivated"),
                            ("member_reinstated", "Member Reinstated"),
                            ("dues_payment_received", "Dues Payment Received"),
                            ("dues_payment_failed", "Dues Payment Failed"),
                            ("strike_fund_updated", "Strike Fund Updated"),
                            ("settlement_recorded", "Settlement Recorded"),
                            ("vote_cast", "Vote Cast"),
                            ("election_started", "Election Started"),
                            ("election_completed", "Election Completed"),
                            ("governance_action", "Governance Action"),
                            ("policy_changed", "Policy Changed"),
                            ("integration_registered", "Integration Registered"),
                            ("integration_dispatched", "Integration Dispatched"),
                            ("integration_failed", "Integration Failed"),
                            ("integration_dead_lettered", "Integration Dead-Lettered"),
                            ("webhook_received", "Webhook Received"),
                            (
                                "compliance_snapshot_created",
                                "Compliance Snapshot Created",
                            ),
                            ("evidence_pack_exported", "Evidence Pack Exported"),
                            ("data_subject_request", "Data Subject Request"),
                            ("break_glass_activated", "Break-Glass Activated"),
                            (
                                "privilege_escalation_attempt",
                                "Privilege Escalation Attempt",
                            ),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("system_health_degraded", "System Health Degraded"),
                            ("system_health_recovered", "System Health Recovered"),
                            ("custom", "Custom Event"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "org_id",
                    models.UUIDField(db_index=True, help_text="Tenant organization ID"),
                ),
                (
                    "actor_id",
                    models.CharField(
                        help_text="User ID or 'system' for automated events",
                        max_length=255,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Event-specific data"),
                ),
                (
                    "signature_hash",
                    models.CharField(
                        help_text="SHA-256 of canonical event representation",
                        max_length=64,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Request correlation ID for tracing",
                        max_length=64,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (source, version, etc.)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "domain_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["org_id", "event_type"], name="idx_events_org_type"
                    ),
                    models.Index(
                        fields=["org_id", "created_at"], name="idx_events_org_time"
                    ),
                    models.Index(
                        fields=["actor_id", "created_at"], name="idx_events_actor_time"
                    ),
                    models.Index(
                        fields=["correlation_id"], name="idx_events_correlation"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvidencePack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_id", models.UUIDField(db_index=True)),
                (
                    "pack_type",
                    models.CharField(
                        choices=[
                            ("governance_full", "Full Governance Pack"),
                            ("grievance_case", "Grievance Case Pack"),
                            ("compliance_audit", "Compliance Audit Pack"),
                            ("election_record", "Election Record Pack"),
                            ("financial_review", "Financial Review Pack"),
                            ("data_subject_request", "Data Subject Request Pack"),
                            ("custom", "Custom Pack"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft — collecting artifacts"),
                            ("sealed", "Sealed — integrity verified"),
                            ("exported", "Exported — delivered to requester"),
                            ("expired", "Expired — retention period elapsed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "checksum_manifest",
                    models.JSONField(
                        default=dict,
                        help_text="SHA-256 checksums for each artifact in the pack",
                    ),
                ),
                (
                    "pack_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 of the entire manifest (seal hash)",
                        max_length=64,
                    ),
                ),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                ("sealed_by", models.CharField(blank=True, default="", max_length=255)),
                ("artifact_count", models.PositiveIntegerField(default=0)),
                ("total_size_bytes", models.BigIntegerField(default=0)),
                (
                    "requested_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "evidence_packs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["org_id", "status"], name="idx_evpack_org_status"
                    ),
                    models.Index(
                        fields=["org_id", "pack_type"], name="idx_evpack_org_type"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntegrationRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_id",
                    models.UUIDField(db_index=True, help_text="Tenant organization ID"),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("webhook_inbound", "Webhook — Inbound"),
                            ("webhook_outbound", "Webhook — Outbound"),
                            ("api_push", "API — Push"),
                            ("api_pull", "API — Pull"),
                            ("email", "Email Provider"),
                            ("sms", "SMS Provider"),
                            ("crm", "CRM System"),
                            ("payment", "Payment Processor"),
                            ("government", "Government System"),
                            ("document_storage", "Document Storage"),
                            ("messaging", "Messaging Platform"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable label", max_length=255),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Remote endpoint URL",
                        max_length=2048,
                    ),
                ),
                (
                    "secret",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HMAC secret or API key (encrypted at rest via app-layer)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("degraded", "Degraded"),
                            ("failed", "Failed"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "retry_policy",
                    models.CharField(
                        choices=[
                            ("exponential_backoff", "Exponential Backoff"),
                            ("linear", "Linear"),
                            ("fixed", "Fixed Interval"),
                            ("none", "No Retry"),
                        ],
                        default="exponential_backoff",
                        max_length=32,
                    ),
                ),
                ("max_retries", models.PositiveSmallIntegerField(default=5)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_reason", models.TextField(blank=True, default="")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Provider-specific config"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "integration_registry",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["org_id", "integration_type"],
                        name="idx_intreg_org_type",
                    ),
                    models.Index(
                        fields=["org_id", "status"], name="idx_intreg_org_status"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org_id", "integration_type", "endpoint_url"),
                        name="uq_intreg_org_type_url",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EvidenceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("audit_log", "Audit Log Entry"),
                            ("domain_event", "Domain Event"),
                            ("case_record", "Case Record"),
                            ("governance_action", "Governance Action"),
                            ("vote_record", "Vote Record"),
                            ("compliance_check", "Compliance Check"),
                            ("attachment", "File Attachment"),
                            ("summary", "Generated Summary"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="UUID or identifier of the source record",
                        max_length=255,
                    ),
                ),
                ("content", models.JSONField(help_text="Serialized artifact content")),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 of serialized content", max_length=64
                    ),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="services.evidencepack",
                    ),
                ),
            ],
            options={
                "db_table": "evidence_artifacts",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["pack", "artifact_type"], name="idx_evart_pack_type"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IntegrationIdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of canonical request body",
                        max_length=64,
                    ),
                ),
                ("org_id", models.UUIDField(db_index=True)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="HTTP status of the original response",
                        null=True,
                    ),
                ),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Discard after this instant (default: created_at + 24 h)"
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_keys",
                        to="services.integrationregistry",
                    ),
                ),
            ],
            options={
                "db_table": "integration_idempotency_keys",
                "indexes": [
                    models.Index(
                        fields=["request_hash", "org_id"], name="idx_idempkey_hash_org"
                    ),
                    models.Index(fields=["expires_at"], name="idx_idempkey_expires"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "expires_at__gte",
                                datetime.datetime(
                                    2026,
                                    3,
                                    4,
                                    6,
                                    5,
                                    31,
                                    136934,
                                    tzinfo=datetime.timezone.utc,
                                ),
                            )
                        ),
                        fields=("request_hash", "org_id"),
                        name="uq_idempkey_hash_org",
                    )
                ],
            },
        ),
    ]
