# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClaimDeadlines",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ClaimDeadlines",
                "db_table": "claim_deadlines",
            },
        ),
        migrations.CreateModel(
            name="ClaimPrecedentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_id", models.UUIDField()),
                (
                    "precedent_matches",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "success_probability",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "ClaimPrecedentAnalysis",
                "db_table": "claim_precedent_analysis",
            },
        ),
        migrations.CreateModel(
            name="Claims",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "claim_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Claims",
                "db_table": "claims",
            },
        ),
        migrations.CreateModel(
            name="DeadlineAlerts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DeadlineAlerts",
                "db_table": "deadline_alerts",
            },
        ),
        migrations.CreateModel(
            name="DeadlineExtensions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DeadlineExtensions",
                "db_table": "deadline_extensions",
            },
        ),
        migrations.CreateModel(
            name="DeadlineRules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DeadlineRules",
                "db_table": "deadline_rules",
            },
        ),
        migrations.CreateModel(
            name="DefensibilityPacks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pack_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("case_id", models.UUIDField()),
                (
                    "case_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "DefensibilityPacks",
                "db_table": "defensibility_packs",
            },
        ),
        migrations.CreateModel(
            name="Grievances",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grievance_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Grievances",
                "db_table": "grievances",
            },
        ),
        migrations.CreateModel(
            name="GrievanceStages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "GrievanceStages",
                "db_table": "grievance_stages",
            },
        ),
        migrations.CreateModel(
            name="GrievanceWorkflows",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "GrievanceWorkflows",
                "db_table": "grievance_workflows",
            },
        ),
        migrations.CreateModel(
            name="PackDownloadLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("log_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("pack_id", models.UUIDField()),
                (
                    "case_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "PackDownloadLog",
                "db_table": "pack_download_log",
            },
        ),
        migrations.CreateModel(
            name="PackVerificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verification_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("pack_id", models.UUIDField()),
                (
                    "case_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "PackVerificationLog",
                "db_table": "pack_verification_log",
            },
        ),
        migrations.CreateModel(
            name="ClaimUpdates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("update_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_updates_claim_set",
                        to="grievances.claims",
                    ),
                ),
            ],
            options={
                "verbose_name": "ClaimUpdates",
                "db_table": "claim_updates",
            },
        ),
        migrations.CreateModel(
            name="GrievanceAssignments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_assignments_claim_set",
                        to="grievances.claims",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceAssignments",
                "db_table": "grievance_assignments",
            },
        ),
        migrations.CreateModel(
            name="GrievanceCommunications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "communication_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_communications_claim_set",
                        to="grievances.claims",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceCommunications",
                "db_table": "grievance_communications",
            },
        ),
        migrations.CreateModel(
            name="GrievanceDocuments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "document_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_documents_claim_set",
                        to="grievances.claims",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceDocuments",
                "db_table": "grievance_documents",
            },
        ),
        migrations.CreateModel(
            name="GrievanceResponses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response_number", models.IntegerField()),
                (
                    "responding_party",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_responses_grievance_set",
                        to="grievances.grievances",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceResponses",
                "db_table": "grievance_responses",
            },
        ),
        migrations.CreateModel(
            name="GrievanceDeadlines",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deadline_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_deadlines_grievance_set",
                        to="grievances.grievances",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceDeadlines",
                "db_table": "grievance_deadlines",
            },
        ),
        migrations.CreateModel(
            name="Arbitrations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arbitration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arbitrations_grievance_set",
                        to="grievances.grievances",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arbitrations",
                "db_table": "arbitrations",
            },
        ),
        migrations.CreateModel(
            name="GrievanceSettlements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "settlement_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_settlements_claim_set",
                        to="grievances.claims",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceSettlements",
                "db_table": "grievance_settlements",
            },
        ),
        migrations.CreateModel(
            name="GrievanceTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_timeline_grievance_set",
                        to="grievances.grievances",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceTimeline",
                "db_table": "grievance_timeline",
            },
        ),
        migrations.CreateModel(
            name="GrievanceTransitions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("trigger_type", models.TextField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "transitioned_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_transitions_claim_set",
                        to="grievances.claims",
                    ),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_transitions_from_stage_set",
                        to="grievances.grievancestages",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_transitions_to_stage_set",
                        to="grievances.grievancestages",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceTransitions",
                "db_table": "grievance_transitions",
            },
        ),
        migrations.CreateModel(
            name="GrievanceApprovals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "transition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_approvals_transition_set",
                        to="grievances.grievancetransitions",
                    ),
                ),
            ],
            options={
                "verbose_name": "GrievanceApprovals",
                "db_table": "grievance_approvals",
            },
        ),
        migrations.AddField(
            model_name="grievancestages",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grievance_stages_workflow_set",
                to="grievances.grievanceworkflows",
            ),
        ),
        migrations.CreateModel(
            name="Settlements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[
                            ("monetary", "Monetary"),
                            ("non_monetary", "Non Monetary"),
                            ("policy_change", "Policy Change"),
                            (" reinstatement", " Reinstatement"),
                            ("apology", "Apology"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "arbitration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements_arbitration_set",
                        to="grievances.arbitrations",
                    ),
                ),
                (
                    "grievance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements_grievance_set",
                        to="grievances.grievances",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settlements",
                "db_table": "settlements",
            },
        ),
    ]
