# Generated by Django 5.1.15 on 2026-02-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'ordering': ['-created_at'], 'verbose_name': 'Claims'},
        ),
        migrations.AddField(
            model_name='claims',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='claim_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='claim_type',
            field=models.CharField(blank=True, choices=[('grievance_discipline', 'Grievance — Discipline'), ('grievance_schedule', 'Grievance — Schedule'), ('grievance_pay', 'Grievance — Pay'), ('workplace_safety', 'Workplace Safety'), ('discrimination_age', 'Discrimination — Age'), ('discrimination_gender', 'Discrimination — Gender'), ('discrimination_race', 'Discrimination — Race'), ('discrimination_disability', 'Discrimination — Disability'), ('discrimination_other', 'Discrimination — Other'), ('harassment_sexual', 'Harassment — Sexual'), ('harassment_workplace', 'Harassment — Workplace'), ('harassment_verbal', 'Harassment — Verbal'), ('harassment_physical', 'Harassment — Physical'), ('wage_dispute', 'Wage Dispute'), ('contract_dispute', 'Contract Dispute'), ('retaliation', 'Retaliation'), ('wrongful_termination', 'Wrongful Termination'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='complexity_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='court_costs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='desired_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='filed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='legal_costs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='member_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='merit_confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='precedent_match',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='previous_report_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='previously_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claims',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='claims',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claims',
            name='resolution_outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='settlement_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('investigation', 'Investigation'), ('pending_documentation', 'Pending Documentation'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='submitted', max_length=30),
        ),
        migrations.AddField(
            model_name='claims',
            name='voice_transcriptions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='witness_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='witnesses_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claims',
            name='claim_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='claims',
            index=models.Index(fields=['organization_id'], name='idx_claims_org'),
        ),
        migrations.AddIndex(
            model_name='claims',
            index=models.Index(fields=['member_id'], name='idx_claims_member'),
        ),
        migrations.AddIndex(
            model_name='claims',
            index=models.Index(fields=['status'], name='idx_claims_status'),
        ),
    ]
