# Generated by Django 5.1.15 on 2026-02-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_expand_claims_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievances',
            options={'ordering': ['-created_at'], 'verbose_name': 'Grievances'},
        ),
        migrations.AddField(
            model_name='grievances',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='cba_article',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='cba_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='cba_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='desired_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='employer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='employer_rep_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='filed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='grievant_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='grievant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='grievant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='group_grievance_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='has_legal_implications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievances',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='is_arbitration_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievances',
            name='is_confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievances',
            name='is_group_grievance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievances',
            name='last_updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='grievances',
            name='related_grievance_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('response_due', 'Response Due'), ('response_received', 'Response Received'), ('escalated', 'Escalated'), ('mediation', 'Mediation'), ('arbitration', 'Arbitration'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn'), ('denied', 'Denied'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='grievances',
            name='step',
            field=models.CharField(blank=True, choices=[('step_1', 'Step 1'), ('step_2', 'Step 2'), ('step_3', 'Step 3'), ('final', 'Final'), ('arbitration', 'Arbitration')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='timeline',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('group', 'Group'), ('policy', 'Policy'), ('contract', 'Contract'), ('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('safety', 'Safety'), ('seniority', 'Seniority'), ('discipline', 'Discipline'), ('termination', 'Termination'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='union_rep_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='workplace_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievances',
            name='workplace_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='grievance_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='grievances',
            index=models.Index(fields=['organization_id'], name='idx_grievances_org'),
        ),
        migrations.AddIndex(
            model_name='grievances',
            index=models.Index(fields=['status'], name='idx_grievances_status'),
        ),
        migrations.AddIndex(
            model_name='grievances',
            index=models.Index(fields=['grievant_id'], name='idx_grievances_grievant'),
        ),
        migrations.AddIndex(
            model_name='grievances',
            index=models.Index(fields=['response_deadline'], name='idx_grievances_deadline'),
        ),
    ]
