# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "AutomationRules",
                "db_table": "automation_rules",
            },
        ),
        migrations.CreateModel(
            name="ExternalAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalAccounts",
                "db_table": "external_accounts",
            },
        ),
        migrations.CreateModel(
            name="ExternalBenefitCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalBenefitCoverage",
                "db_table": "external_benefit_coverage",
            },
        ),
        migrations.CreateModel(
            name="ExternalBenefitDependents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalBenefitDependents",
                "db_table": "external_benefit_dependents",
            },
        ),
        migrations.CreateModel(
            name="ExternalBenefitEnrollments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalBenefitEnrollments",
                "db_table": "external_benefit_enrollments",
            },
        ),
        migrations.CreateModel(
            name="ExternalBenefitPlans",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalBenefitPlans",
                "db_table": "external_benefit_plans",
            },
        ),
        migrations.CreateModel(
            name="ExternalBenefitUtilization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalBenefitUtilization",
                "db_table": "external_benefit_utilization",
            },
        ),
        migrations.CreateModel(
            name="ExternalCommunicationChannels",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalCommunicationChannels",
                "db_table": "external_communication_channels",
            },
        ),
        migrations.CreateModel(
            name="ExternalCommunicationFiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalCommunicationFiles",
                "db_table": "external_communication_files",
            },
        ),
        migrations.CreateModel(
            name="ExternalCommunicationMessages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalCommunicationMessages",
                "db_table": "external_communication_messages",
            },
        ),
        migrations.CreateModel(
            name="ExternalCommunicationUsers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalCommunicationUsers",
                "db_table": "external_communication_users",
            },
        ),
        migrations.CreateModel(
            name="ExternalCustomers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalCustomers",
                "db_table": "external_customers",
            },
        ),
        migrations.CreateModel(
            name="ExternalDepartments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalDepartments",
                "db_table": "external_departments",
            },
        ),
        migrations.CreateModel(
            name="ExternalDocumentFiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalDocumentFiles",
                "db_table": "external_document_files",
            },
        ),
        migrations.CreateModel(
            name="ExternalDocumentLibraries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalDocumentLibraries",
                "db_table": "external_document_libraries",
            },
        ),
        migrations.CreateModel(
            name="ExternalDocumentPermissions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalDocumentPermissions",
                "db_table": "external_document_permissions",
            },
        ),
        migrations.CreateModel(
            name="ExternalDocumentSites",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalDocumentSites",
                "db_table": "external_document_sites",
            },
        ),
        migrations.CreateModel(
            name="ExternalEmployees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalEmployees",
                "db_table": "external_employees",
            },
        ),
        migrations.CreateModel(
            name="ExternalInsuranceBeneficiaries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalInsuranceBeneficiaries",
                "db_table": "external_insurance_beneficiaries",
            },
        ),
        migrations.CreateModel(
            name="ExternalInsuranceClaims",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalInsuranceClaims",
                "db_table": "external_insurance_claims",
            },
        ),
        migrations.CreateModel(
            name="ExternalInsurancePolicies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalInsurancePolicies",
                "db_table": "external_insurance_policies",
            },
        ),
        migrations.CreateModel(
            name="ExternalInvoices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalInvoices",
                "db_table": "external_invoices",
            },
        ),
        migrations.CreateModel(
            name="ExternalLmsCompletions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalLmsCompletions",
                "db_table": "external_lms_completions",
            },
        ),
        migrations.CreateModel(
            name="ExternalLmsCourses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalLmsCourses",
                "db_table": "external_lms_courses",
            },
        ),
        migrations.CreateModel(
            name="ExternalLmsEnrollments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalLmsEnrollments",
                "db_table": "external_lms_enrollments",
            },
        ),
        migrations.CreateModel(
            name="ExternalLmsLearners",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalLmsLearners",
                "db_table": "external_lms_learners",
            },
        ),
        migrations.CreateModel(
            name="ExternalLmsProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalLmsProgress",
                "db_table": "external_lms_progress",
            },
        ),
        migrations.CreateModel(
            name="ExternalPayments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalPayments",
                "db_table": "external_payments",
            },
        ),
        migrations.CreateModel(
            name="ExternalPositions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalPositions",
                "db_table": "external_positions",
            },
        ),
        migrations.CreateModel(
            name="FailedLoginAttempts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "FailedLoginAttempts",
                "db_table": "failed_login_attempts",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseArticles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "KnowledgeBaseArticles",
                "db_table": "knowledge_base_articles",
            },
        ),
        migrations.CreateModel(
            name="RateLimitEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("identifier", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "RateLimitEvents",
                "db_table": "rate_limit_events",
            },
        ),
        migrations.CreateModel(
            name="SlaPolicies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "SlaPolicies",
                "db_table": "sla_policies",
            },
        ),
        migrations.CreateModel(
            name="SupportTickets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "SupportTickets",
                "db_table": "support_tickets",
            },
        ),
        migrations.CreateModel(
            name="AlertEscalations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_escalations_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlertEscalations",
                "db_table": "alert_escalations",
            },
        ),
        migrations.CreateModel(
            name="AlertRules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlertRules",
                "db_table": "alert_rules",
            },
        ),
        migrations.CreateModel(
            name="AlertRecipients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_recipients_alert_rule_set",
                        to="core.alertrules",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlertRecipients",
                "db_table": "alert_recipients",
            },
        ),
        migrations.CreateModel(
            name="AlertExecutions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_executions_alert_rule_set",
                        to="core.alertrules",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlertExecutions",
                "db_table": "alert_executions",
            },
        ),
        migrations.CreateModel(
            name="AlertConditions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_conditions_alert_rule_set",
                        to="core.alertrules",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlertConditions",
                "db_table": "alert_conditions",
            },
        ),
        migrations.CreateModel(
            name="AlertActions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_actions_alert_rule_set",
                        to="core.alertrules",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlertActions",
                "db_table": "alert_actions",
            },
        ),
        migrations.CreateModel(
            name="ApiAccessTokens",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_access_tokens_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "ApiAccessTokens",
                "db_table": "api_access_tokens",
            },
        ),
        migrations.CreateModel(
            name="ApiIntegrations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_integrations_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "ApiIntegrations",
                "db_table": "api_integrations",
            },
        ),
        migrations.CreateModel(
            name="AuditLogs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "AuditLogs",
                "db_table": "audit_logs",
            },
        ),
        migrations.CreateModel(
            name="AutomationExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "triggered_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_execution_log_rule_set",
                        to="core.automationrules",
                    ),
                ),
            ],
            options={
                "verbose_name": "AutomationExecutionLog",
                "db_table": "automation_execution_log",
            },
        ),
        migrations.CreateModel(
            name="AutomationSchedules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_schedules_rule_set",
                        to="core.automationrules",
                    ),
                ),
            ],
            options={
                "verbose_name": "AutomationSchedules",
                "db_table": "automation_schedules",
            },
        ),
        migrations.CreateModel(
            name="IntegrationApiKeys",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_api_keys_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntegrationApiKeys",
                "db_table": "integration_api_keys",
            },
        ),
        migrations.CreateModel(
            name="IntegrationConfigs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_configs_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntegrationConfigs",
                "db_table": "integration_configs",
            },
        ),
        migrations.CreateModel(
            name="IntegrationSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_sync_log_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntegrationSyncLog",
                "db_table": "integration_sync_log",
            },
        ),
        migrations.CreateModel(
            name="IntegrationSyncLogs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_sync_logs_integration_set",
                        to="core.apiintegrations",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntegrationSyncLogs",
                "db_table": "integration_sync_logs",
            },
        ),
        migrations.CreateModel(
            name="IntegrationSyncSchedules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_sync_schedules_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntegrationSyncSchedules",
                "db_table": "integration_sync_schedules",
            },
        ),
        migrations.CreateModel(
            name="IntegrationWebhooks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_webhooks_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntegrationWebhooks",
                "db_table": "integration_webhooks",
            },
        ),
        migrations.CreateModel(
            name="SecurityEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "SecurityEvents",
                "db_table": "security_events",
            },
        ),
        migrations.CreateModel(
            name="TicketComments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_comments_ticket_set",
                        to="core.supporttickets",
                    ),
                ),
            ],
            options={
                "verbose_name": "TicketComments",
                "db_table": "ticket_comments",
            },
        ),
        migrations.CreateModel(
            name="TicketHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_history_ticket_set",
                        to="core.supporttickets",
                    ),
                ),
            ],
            options={
                "verbose_name": "TicketHistory",
                "db_table": "ticket_history",
            },
        ),
        migrations.CreateModel(
            name="WebhookDeliveries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_deliveries_webhook_set",
                        to="core.integrationwebhooks",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebhookDeliveries",
                "db_table": "webhook_deliveries",
            },
        ),
        migrations.CreateModel(
            name="WebhookEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebhookEvents",
                "db_table": "webhook_events",
            },
        ),
        migrations.CreateModel(
            name="WebhookSubscriptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_subscriptions_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebhookSubscriptions",
                "db_table": "webhook_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="WorkflowDefinitions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_definitions_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkflowDefinitions",
                "db_table": "workflow_definitions",
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecutions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_executions_workflow_definition_set",
                        to="core.workflowdefinitions",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkflowExecutions",
                "db_table": "workflow_executions",
            },
        ),
    ]
