# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "AwardTemplates",
                "db_table": "award_templates",
            },
        ),
        migrations.CreateModel(
            name="BargainingUnits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "BargainingUnits",
                "db_table": "bargaining_units",
            },
        ),
        migrations.CreateModel(
            name="BudgetPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "BudgetPool",
                "db_table": "budget_pool",
            },
        ),
        migrations.CreateModel(
            name="Calendars",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Calendars",
                "db_table": "calendars",
            },
        ),
        migrations.CreateModel(
            name="CommitteeMemberships",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("committee_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CommitteeMemberships",
                "db_table": "committee_memberships",
            },
        ),
        migrations.CreateModel(
            name="Committees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Committees",
                "db_table": "committees",
            },
        ),
        migrations.CreateModel(
            name="CongressMemberships",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CongressMemberships",
                "db_table": "congress_memberships",
            },
        ),
        migrations.CreateModel(
            name="CourseRegistrations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("member_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "CourseRegistrations",
                "db_table": "course_registrations",
            },
        ),
        migrations.CreateModel(
            name="CourseSessions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                (
                    "session_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CourseSessions",
                "db_table": "course_sessions",
            },
        ),
        migrations.CreateModel(
            name="Employers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Employers",
                "db_table": "employers",
            },
        ),
        migrations.CreateModel(
            name="ExternalCalendarConnections",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ExternalCalendarConnections",
                "db_table": "external_calendar_connections",
            },
        ),
        migrations.CreateModel(
            name="FederationCampaigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("federation_id", models.UUIDField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "FederationCampaigns",
                "db_table": "federation_campaigns",
            },
        ),
        migrations.CreateModel(
            name="FederationCommunications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("federation_id", models.UUIDField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "FederationCommunications",
                "db_table": "federation_communications",
            },
        ),
        migrations.CreateModel(
            name="FederationExecutives",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("federation_id", models.UUIDField()),
                (
                    "profile_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "FederationExecutives",
                "db_table": "federation_executives",
            },
        ),
        migrations.CreateModel(
            name="FederationMeetings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("federation_id", models.UUIDField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "FederationMeetings",
                "db_table": "federation_meetings",
            },
        ),
        migrations.CreateModel(
            name="FederationMemberships",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("federation_id", models.UUIDField()),
                ("union_organization_id", models.UUIDField()),
                ("status", models.TextField(default="active")),
                (
                    "membership_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "FederationMemberships",
                "db_table": "federation_memberships",
            },
        ),
        migrations.CreateModel(
            name="FederationRemittances",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("federation_id", models.UUIDField()),
                ("from_organization_id", models.UUIDField()),
                ("to_organization_id", models.UUIDField()),
                ("membership_id", models.UUIDField(blank=True, null=True)),
                ("per_capita_remittance_id", models.UUIDField(blank=True, null=True)),
                ("remittance_month", models.IntegerField()),
                ("remittance_year", models.IntegerField()),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField()),
                ("total_members", models.IntegerField()),
                ("remittable_members", models.IntegerField()),
                (
                    "per_capita_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "FederationRemittances",
                "db_table": "federation_remittances",
            },
        ),
        migrations.CreateModel(
            name="FederationResources",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("federation_id", models.UUIDField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "FederationResources",
                "db_table": "federation_resources",
            },
        ),
        migrations.CreateModel(
            name="Federations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Federations",
                "db_table": "federations",
            },
        ),
        migrations.CreateModel(
            name="FieldNotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "FieldNotes",
                "db_table": "field_notes",
            },
        ),
        migrations.CreateModel(
            name="MeetingRooms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MeetingRooms",
                "db_table": "meeting_rooms",
            },
        ),
        migrations.CreateModel(
            name="MemberAddresses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "MemberAddresses",
                "db_table": "member_addresses",
            },
        ),
        migrations.CreateModel(
            name="MemberCertifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("member_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "MemberCertifications",
                "db_table": "member_certifications",
            },
        ),
        migrations.CreateModel(
            name="MemberLocationConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "MemberLocationConsent",
                "db_table": "member_location_consent",
            },
        ),
        migrations.CreateModel(
            name="MemberRelationshipScores",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MemberRelationshipScores",
                "db_table": "member_relationship_scores",
            },
        ),
        migrations.CreateModel(
            name="MemberSegments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("filters", models.JSONField(default=dict)),
                ("created_by", models.TextField()),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "MemberSegments",
                "db_table": "member_segments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizerTasks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OrganizerTasks",
                "db_table": "organizer_tasks",
            },
        ),
        migrations.CreateModel(
            name="OutreachEnrollments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OutreachEnrollments",
                "db_table": "outreach_enrollments",
            },
        ),
        migrations.CreateModel(
            name="OutreachSequences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OutreachSequences",
                "db_table": "outreach_sequences",
            },
        ),
        migrations.CreateModel(
            name="OutreachStepsLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OutreachStepsLog",
                "db_table": "outreach_steps_log",
            },
        ),
        migrations.CreateModel(
            name="Polls",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Polls",
                "db_table": "polls",
            },
        ),
        migrations.CreateModel(
            name="PollVotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PollVotes",
                "db_table": "poll_votes",
            },
        ),
        migrations.CreateModel(
            name="ProgramEnrollments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("member_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ProgramEnrollments",
                "db_table": "program_enrollments",
            },
        ),
        migrations.CreateModel(
            name="RecognitionAwards",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RecognitionAwards",
                "db_table": "recognition_awards",
            },
        ),
        migrations.CreateModel(
            name="RecognitionAwardTypes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RecognitionAwardTypes",
                "db_table": "recognition_award_types",
            },
        ),
        migrations.CreateModel(
            name="RecognitionPrograms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RecognitionPrograms",
                "db_table": "recognition_programs",
            },
        ),
        migrations.CreateModel(
            name="RewardBudgetEnvelopes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RewardBudgetEnvelopes",
                "db_table": "reward_budget_envelopes",
            },
        ),
        migrations.CreateModel(
            name="RewardRedemptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RewardRedemptions",
                "db_table": "reward_redemptions",
            },
        ),
        migrations.CreateModel(
            name="RewardWalletLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "RewardWalletLedger",
                "db_table": "reward_wallet_ledger",
            },
        ),
        migrations.CreateModel(
            name="RoleTenureHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "RoleTenureHistory",
                "db_table": "role_tenure_history",
            },
        ),
        migrations.CreateModel(
            name="StewardAssignments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "StewardAssignments",
                "db_table": "steward_assignments",
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SurveyAnswers",
                "db_table": "survey_answers",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SurveyQuestions",
                "db_table": "survey_questions",
            },
        ),
        migrations.CreateModel(
            name="SurveyResponses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SurveyResponses",
                "db_table": "survey_responses",
            },
        ),
        migrations.CreateModel(
            name="Surveys",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Surveys",
                "db_table": "surveys",
            },
        ),
        migrations.CreateModel(
            name="TaskComments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "TaskComments",
                "db_table": "task_comments",
            },
        ),
        migrations.CreateModel(
            name="TrainingCourses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "course_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "TrainingCourses",
                "db_table": "training_courses",
            },
        ),
        migrations.CreateModel(
            name="TrainingPrograms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "program_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "TrainingPrograms",
                "db_table": "training_programs",
            },
        ),
        migrations.CreateModel(
            name="VotingSessions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "VotingSessions",
                "db_table": "voting_sessions",
            },
        ),
        migrations.CreateModel(
            name="Worksites",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Worksites",
                "db_table": "worksites",
            },
        ),
        migrations.CreateModel(
            name="AwardHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award_history_template_set",
                        to="unions.awardtemplates",
                    ),
                ),
            ],
            options={
                "verbose_name": "AwardHistory",
                "db_table": "award_history",
            },
        ),
        migrations.CreateModel(
            name="BudgetReservations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reserved_amount", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_reservations_pool_set",
                        to="unions.budgetpool",
                    ),
                ),
            ],
            options={
                "verbose_name": "BudgetReservations",
                "db_table": "budget_reservations",
            },
        ),
        migrations.CreateModel(
            name="CalendarEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events_calendar_set",
                        to="unions.calendars",
                    ),
                ),
            ],
            options={
                "verbose_name": "CalendarEvents",
                "db_table": "calendar_events",
            },
        ),
        migrations.CreateModel(
            name="CalendarSharing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_sharing_calendar_set",
                        to="unions.calendars",
                    ),
                ),
            ],
            options={
                "verbose_name": "CalendarSharing",
                "db_table": "calendar_sharing",
            },
        ),
        migrations.CreateModel(
            name="CardSigningEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_signing_events_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "CardSigningEvents",
                "db_table": "card_signing_events",
            },
        ),
        migrations.CreateModel(
            name="EmployerResponses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_responses_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "EmployerResponses",
                "db_table": "employer_responses",
            },
        ),
        migrations.CreateModel(
            name="EventAttendees",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendees_event_set",
                        to="unions.calendarevents",
                    ),
                ),
            ],
            options={
                "verbose_name": "EventAttendees",
                "db_table": "event_attendees",
            },
        ),
        migrations.CreateModel(
            name="EventReminders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reminders_event_set",
                        to="unions.calendarevents",
                    ),
                ),
            ],
            options={
                "verbose_name": "EventReminders",
                "db_table": "event_reminders",
            },
        ),
        migrations.CreateModel(
            name="FieldOrganizerActivities",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_organizer_activities_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "FieldOrganizerActivities",
                "db_table": "field_organizer_activities",
            },
        ),
        migrations.CreateModel(
            name="Holidays",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holidays",
                "db_table": "holidays",
            },
        ),
        migrations.CreateModel(
            name="JobClassifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bargaining_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_classifications_bargaining_unit_set",
                        to="unions.bargainingunits",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_classifications_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "JobClassifications",
                "db_table": "job_classifications",
            },
        ),
        migrations.CreateModel(
            name="MemberEmployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("layoff", "Layoff"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("retired", "Retired"),
                            ("deceased", "Deceased"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("casual", "Casual"),
                            ("seasonal", "Seasonal"),
                            ("temporary", "Temporary"),
                            ("contract", "Contract"),
                            ("probationary", "Probationary"),
                        ],
                        default="full_time",
                        max_length=22,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("seniority_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                (
                    "seniority_years",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "bargaining_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_employment_bargaining_unit_set",
                        to="unions.bargainingunits",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_employment_employer_set",
                        to="unions.employers",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_employment_member_set",
                        to="auth_core.organizationmembers",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_employment_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
                (
                    "worksite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_employment_worksite_set",
                        to="unions.worksites",
                    ),
                ),
            ],
            options={
                "verbose_name": "MemberEmployment",
                "db_table": "member_employment",
            },
        ),
        migrations.CreateModel(
            name="EmploymentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_history_member_set",
                        to="auth_core.organizationmembers",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_history_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
                (
                    "member_employment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_history_member_employment_set",
                        to="unions.memberemployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "EmploymentHistory",
                "db_table": "employment_history",
            },
        ),
        migrations.CreateModel(
            name="MemberLeaves",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick"),
                            ("maternity", "Maternity"),
                            ("paternity", "Paternity"),
                            ("parental", "Parental"),
                            ("bereavement", "Bereavement"),
                            ("medical", "Medical"),
                            ("disability", "Disability"),
                            ("union_business", "Union Business"),
                            ("unpaid", "Unpaid"),
                            ("lwop", "Lwop"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_leaves_member_set",
                        to="auth_core.organizationmembers",
                    ),
                ),
                (
                    "member_employment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_leaves_member_employment_set",
                        to="unions.memberemployment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_leaves_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "MemberLeaves",
                "db_table": "member_leaves",
            },
        ),
        migrations.CreateModel(
            name="NlrbClrbFilings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nlrb_clrb_filings_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "NlrbClrbFilings",
                "db_table": "nlrb_clrb_filings",
            },
        ),
        migrations.CreateModel(
            name="OrganizingCampaignMilestones",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizing_campaign_milestones_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrganizingCampaignMilestones",
                "db_table": "organizing_campaign_milestones",
            },
        ),
        migrations.CreateModel(
            name="OrganizingCampaigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizing_campaigns_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrganizingCampaigns",
                "db_table": "organizing_campaigns",
            },
        ),
        migrations.CreateModel(
            name="OrganizingContacts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizing_contacts_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrganizingContacts",
                "db_table": "organizing_contacts",
            },
        ),
        migrations.CreateModel(
            name="RoomBookings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings_room_set",
                        to="unions.meetingrooms",
                    ),
                ),
            ],
            options={
                "verbose_name": "RoomBookings",
                "db_table": "room_bookings",
            },
        ),
        migrations.CreateModel(
            name="SegmentExecutions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_executions_segment_set",
                        to="unions.membersegments",
                    ),
                ),
            ],
            options={
                "verbose_name": "SegmentExecutions",
                "db_table": "segment_executions",
            },
        ),
        migrations.CreateModel(
            name="SegmentExports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_exports_segment_set",
                        to="unions.membersegments",
                    ),
                ),
            ],
            options={
                "verbose_name": "SegmentExports",
                "db_table": "segment_exports",
            },
        ),
        migrations.CreateModel(
            name="UnionRepresentationVotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="union_representation_votes_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "UnionRepresentationVotes",
                "db_table": "union_representation_votes",
            },
        ),
        migrations.CreateModel(
            name="VotingOptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_options_session_set",
                        to="unions.votingsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "VotingOptions",
                "db_table": "voting_options",
            },
        ),
        migrations.CreateModel(
            name="VotingNotifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_notifications_session_set",
                        to="unions.votingsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "VotingNotifications",
                "db_table": "voting_notifications",
            },
        ),
        migrations.CreateModel(
            name="VotingAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_audit_log_session_set",
                        to="unions.votingsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "VotingAuditLog",
                "db_table": "voting_audit_log",
            },
        ),
        migrations.CreateModel(
            name="Votes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_session_set",
                        to="unions.votingsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Votes",
                "db_table": "votes",
            },
        ),
        migrations.CreateModel(
            name="VoterEligibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_eligibility_session_set",
                        to="unions.votingsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "VoterEligibility",
                "db_table": "voter_eligibility",
            },
        ),
    ]
