/**
 * Nzila OS — Scale Report Artifact Generator
 *
 * Produces a structured JSON + Markdown scale report from
 * ScaleEnvelopeResult data. Designed for procurement artifacts
 * and executive-facing scale proof.
 *
 * @module @nzila/platform-performance/scale-report
 */

import type { ScaleEnvelopeResult, ScalePhaseResult } from './scale-harness'

// ── Types ───────────────────────────────────────────────────────────────────

export interface ScaleReportPhase {
  name: string
  concurrency: number
  rps: number
  totalRequests: number
  p50: number
  p95: number
  p99: number
  errorRate: number
  throughput: number
  budgetViolations: number
  passed: boolean
}

export interface ScaleReportSummary {
  /** Overall pass/fail for the scale envelope */
  verdict: 'PASS' | 'FAIL'
  /** Peak p95 observed across all phases */
  peakP95Ms: number
  /** Peak throughput (requests/min) */
  peakThroughputRpm: number
  /** Degradation ratio: peak p95 / baseline p95 */
  degradationRatio: number
  /** Maximum concurrency tested */
  maxConcurrency: number
  /** Maximum RPS tested */
  maxRps: number
  /** Total synthetic requests across all phases */
  totalRequestsGenerated: number
  /** Number of phases that passed */
  phasesPassedCount: number
  /** Total phases */
  phasesTotalCount: number
}

export interface ScaleReport {
  /** Report format version */
  version: string
  /** Report title */
  title: string
  /** ISO timestamp of generation */
  generatedAt: string
  /** Executive summary */
  summary: ScaleReportSummary
  /** Per-phase breakdown */
  phases: ScaleReportPhase[]
  /** Markdown rendering of the report */
  markdown: string
}

// ── Report Generation ───────────────────────────────────────────────────────

function mapPhase(phase: ScalePhaseResult): ScaleReportPhase {
  return {
    name: phase.profile.name,
    concurrency: phase.profile.concurrency,
    rps: phase.profile.rps,
    totalRequests: phase.totalRequests,
    p50: phase.envelope.p50,
    p95: phase.envelope.p95,
    p99: phase.envelope.p99,
    errorRate: phase.envelope.errorRate,
    throughput: phase.envelope.throughput,
    budgetViolations: phase.budgetViolations,
    passed: phase.passed,
  }
}

function buildSummary(result: ScaleEnvelopeResult): ScaleReportSummary {
  const phases = result.phases
  return {
    verdict: result.passed ? 'PASS' : 'FAIL',
    peakP95Ms: result.peakP95,
    peakThroughputRpm: result.peakThroughput,
    degradationRatio: result.degradationRatio,
    maxConcurrency: Math.max(...phases.map((p) => p.profile.concurrency)),
    maxRps: Math.max(...phases.map((p) => p.profile.rps)),
    totalRequestsGenerated: phases.reduce((sum, p) => sum + p.totalRequests, 0),
    phasesPassedCount: phases.filter((p) => p.passed).length,
    phasesTotalCount: phases.length,
  }
}

function buildMarkdown(summary: ScaleReportSummary, phases: ScaleReportPhase[]): string {
  const lines: string[] = [
    '# Nzila OS — Scale Envelope Report',
    '',
    `**Generated:** ${new Date().toISOString()}`,
    `**Verdict:** ${summary.verdict === 'PASS' ? '✅ PASS' : '❌ FAIL'}`,
    '',
    '## Executive Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Peak P95 Latency | ${summary.peakP95Ms} ms |`,
    `| Peak Throughput | ${summary.peakThroughputRpm} req/min |`,
    `| Degradation Ratio | ${summary.degradationRatio}x |`,
    `| Max Concurrency Tested | ${summary.maxConcurrency} |`,
    `| Max RPS Tested | ${summary.maxRps} |`,
    `| Total Requests Generated | ${summary.totalRequestsGenerated.toLocaleString()} |`,
    `| Phases Passed | ${summary.phasesPassedCount} / ${summary.phasesTotalCount} |`,
    '',
    '## Phase Breakdown',
    '',
    '| Phase | Concurrency | RPS | Requests | P50 | P95 | P99 | Error % | Status |',
    '|-------|-------------|-----|----------|-----|-----|-----|---------|--------|',
  ]

  for (const phase of phases) {
    const status = phase.passed ? '✅' : '❌'
    lines.push(
      `| ${phase.name} | ${phase.concurrency} | ${phase.rps} | ` +
        `${phase.totalRequests.toLocaleString()} | ${phase.p50} ms | ${phase.p95} ms | ` +
        `${phase.p99} ms | ${phase.errorRate}% | ${status} |`,
    )
  }

  lines.push(
    '',
    '## Interpretation',
    '',
    `The platform was tested across ${phases.length} load phases, ramping from ` +
      `${phases[0]?.concurrency ?? 0} to ${summary.maxConcurrency} concurrent users ` +
      `and from ${phases[0]?.rps ?? 0} to ${summary.maxRps} RPS.`,
    '',
    `The degradation ratio of **${summary.degradationRatio}x** indicates the P95 latency ` +
      `increase from baseline to peak load. A ratio below 3.0x is considered acceptable ` +
      `for production-grade platforms.`,
    '',
    '---',
    '*Generated by @nzila/platform-performance scale-report module.*',
  )

  return lines.join('\n')
}

// ── Public API ──────────────────────────────────────────────────────────────

/**
 * Generate a structured scale report from an envelope result.
 * Pure function — no side effects.
 */
export function generateScaleReport(result: ScaleEnvelopeResult): ScaleReport {
  const phases = result.phases.map(mapPhase)
  const summary = buildSummary(result)
  const markdown = buildMarkdown(summary, phases)

  return {
    version: '1.0.0',
    title: 'Nzila OS — Scale Envelope Report',
    generatedAt: new Date().toISOString(),
    summary,
    phases,
    markdown,
  }
}
