/**
 * Zonga domain services — Zonga app.
 *
 * Wires @nzila/zonga-core for creator management, content assets,
 * revenue tracking, payout previews, and audit trail generation.
 * Extended with African regional enums, types, schemas.
 */
import {
  computePayoutPreview,
  buildZongaAuditEvent,
  ZongaAuditAction,
  ZongaEntityType,
  type ZongaAuditEvent,
} from '@nzila/zonga-core/services'

import {
  CreateCreatorSchema,
  CreateContentAssetSchema,
  PublishAssetSchema,
  CreateReleaseSchema,
  RecordRevenueEventSchema,
  PayoutPreviewRequestSchema,
  ZongaOrgContextSchema,
  AudioUploadMetaSchema,
  RoyaltySplitSchema,
  CreateListenerSchema,
  ListenerFollowSchema,
  ListenerFavoriteSchema,
  ListenerActivitySchema,
  CreateEventSchema,
  CreateTicketTypeSchema,
  PurchaseTicketSchema,
  CreatePlaylistSchema,
  AddPlaylistItemSchema,
  CreateModerationCaseSchema,
  ResolveModerationCaseSchema,
  CreateNotificationSchema,
  type CreateCreatorInput,
  type CreateContentAssetInput,
  type RecordRevenueEventInput,
  type PayoutPreviewRequestInput,
  type AudioUploadMetaInput,
  type RoyaltySplitInput,
  type CreateListenerInput,
  type ListenerFollowInput,
  type ListenerFavoriteInput,
  type ListenerActivityInput,
  type CreateEventInput,
  type CreateTicketTypeInput,
  type PurchaseTicketInput,
  type CreatePlaylistInput,
  type AddPlaylistItemInput,
  type CreateModerationCaseInput,
  type ResolveModerationCaseInput,
  type CreateNotificationInput,
} from '@nzila/zonga-core/schemas'

import {
  CreatorStatus,
  CreatorOnboardingStatus,
  AssetType,
  AssetStatus,
  ReleaseStatus,
  ReleaseType,
  RevenueType,
  PayoutStatus,
  PayoutRail,
  LedgerEntryType,
  ZongaCurrency,
  AfricanGenre,
  AudioQuality,
  ZongaLanguage,
  AfricanCountry,
  EventStatus,
  TicketPurchaseStatus,
  PlaylistVisibility,
  PlaylistOwnerType,
  ModerationCaseType,
  ModerationCaseStatus,
  FavoriteEntityType,
  ListenerActivityType,
  NotificationType,
  PayoutPreviewStatus,
} from '@nzila/zonga-core/enums'

import type {
  Creator,
  CreatorRegion,
  ContentAsset,
  Release,
  RevenueEvent,
  Payout,
  PayoutPreview,
  ZongaOrgContext,
  RoyaltySplit,
  AudioUploadResult,
  CreatorAccount,
  Listener,
  ListenerFollow,
  ListenerFavorite,
  ListenerActivity,
  Playlist,
  PlaylistItem,
  ZongaEvent,
  TicketType,
  TicketPurchase,
  ModerationCase,
  IntegritySignal,
  ZongaNotification,
  ReleaseTrack,
  PayoutPreviewRecord,
} from '@nzila/zonga-core/types'

// ── Services ──
export {
  computePayoutPreview,
  buildZongaAuditEvent,
  ZongaAuditAction,
  ZongaEntityType,
}
export type { ZongaAuditEvent }

// ── Schemas (Zod validation) ──
export {
  CreateCreatorSchema,
  CreateContentAssetSchema,
  PublishAssetSchema,
  CreateReleaseSchema,
  RecordRevenueEventSchema,
  PayoutPreviewRequestSchema,
  ZongaOrgContextSchema,
  AudioUploadMetaSchema,
  RoyaltySplitSchema,
  CreateListenerSchema,
  ListenerFollowSchema,
  ListenerFavoriteSchema,
  ListenerActivitySchema,
  CreateEventSchema,
  CreateTicketTypeSchema,
  PurchaseTicketSchema,
  CreatePlaylistSchema,
  AddPlaylistItemSchema,
  CreateModerationCaseSchema,
  ResolveModerationCaseSchema,
  CreateNotificationSchema,
}
export type {
  CreateCreatorInput,
  CreateContentAssetInput,
  RecordRevenueEventInput,
  PayoutPreviewRequestInput,
  AudioUploadMetaInput,
  RoyaltySplitInput,
  CreateListenerInput,
  ListenerFollowInput,
  ListenerFavoriteInput,
  ListenerActivityInput,
  CreateEventInput,
  CreateTicketTypeInput,
  PurchaseTicketInput,
  CreatePlaylistInput,
  AddPlaylistItemInput,
  CreateModerationCaseInput,
  ResolveModerationCaseInput,
  CreateNotificationInput,
}

// ── Enums ──
export {
  CreatorStatus,
  CreatorOnboardingStatus,
  AssetType,
  AssetStatus,
  ReleaseStatus,
  ReleaseType,
  RevenueType,
  PayoutStatus,
  PayoutRail,
  LedgerEntryType,
  ZongaCurrency,
  AfricanGenre,
  AudioQuality,
  ZongaLanguage,
  AfricanCountry,
  EventStatus,
  TicketPurchaseStatus,
  PlaylistVisibility,
  PlaylistOwnerType,
  ModerationCaseType,
  ModerationCaseStatus,
  FavoriteEntityType,
  ListenerActivityType,
  NotificationType,
  PayoutPreviewStatus,
}

// ── Domain types ──
export type {
  Creator,
  CreatorRegion,
  ContentAsset,
  Release,
  RevenueEvent,
  Payout,
  PayoutPreview,
  ZongaOrgContext,
  RoyaltySplit,
  AudioUploadResult,
  CreatorAccount,
  Listener,
  ListenerFollow,
  ListenerFavorite,
  ListenerActivity,
  Playlist,
  PlaylistItem,
  ZongaEvent,
  TicketType,
  TicketPurchase,
  ModerationCase,
  IntegritySignal,
  ZongaNotification,
  ReleaseTrack,
  PayoutPreviewRecord,
}
