# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddressChangeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AddressChangeHistory",
                "db_table": "address_change_history",
            },
        ),
        migrations.CreateModel(
            name="AddressValidationCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_hash", models.TextField(unique=True)),
                ("country_code", models.TextField()),
                ("address_line1", models.TextField()),
                ("locality", models.TextField()),
                ("administrative_area", models.TextField(blank=True, null=True)),
                ("postal_code", models.TextField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=False)),
                ("validated_by", models.TextField()),
                ("confidence", models.TextField(blank=True, null=True)),
                (
                    "corrected_address",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("latitude", models.TextField(blank=True, null=True)),
                ("longitude", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("expires_at", models.DateTimeField()),
                ("hit_count", models.IntegerField(default=1)),
                ("last_hit_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "AddressValidationCache",
                "db_table": "address_validation_cache",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CountryAddressFormats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country_code", models.TextField(unique=True)),
                ("country_name", models.TextField()),
                ("iso3_code", models.TextField(blank=True, null=True)),
                ("locality_label", models.TextField(default="City")),
                (
                    "administrative_area_label",
                    models.TextField(blank=True, default="State", null=True),
                ),
                (
                    "postal_code_label",
                    models.TextField(blank=True, default="Postal Code", null=True),
                ),
                (
                    "sub_administrative_area_label",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "required_fields",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "optional_fields",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("address_format", models.TextField()),
                (
                    "display_order",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("postal_code_required", models.BooleanField(default=False)),
                ("postal_code_pattern", models.TextField(blank=True, null=True)),
                ("postal_code_example", models.TextField(blank=True, null=True)),
                ("postal_code_length", models.IntegerField(blank=True, null=True)),
                (
                    "administrative_areas",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("has_subdivisions", models.BooleanField(default=False)),
                (
                    "validation_rules",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("geocoding_supported", models.BooleanField(default=False)),
                ("preferred_geocoder", models.TextField(blank=True, null=True)),
                ("standardization_provider", models.TextField(blank=True, null=True)),
                ("standardization_available", models.BooleanField(default=False)),
                (
                    "example_addresses",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "CountryAddressFormats",
                "db_table": "country_address_formats",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrossOrgAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "CrossOrgAccessLog",
                "db_table": "cross_org_access_log",
            },
        ),
        migrations.CreateModel(
            name="FeatureFlags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField(unique=True)),
                ("type", models.TextField(default="boolean")),
                ("enabled", models.BooleanField(default=False)),
                ("percentage", models.IntegerField(blank=True, null=True)),
                (
                    "allowed_organizations",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "allowed_users",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "FeatureFlags",
                "db_table": "feature_flags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InternationalAddresses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "InternationalAddresses",
                "db_table": "international_addresses",
            },
        ),
        migrations.CreateModel(
            name="MemberConsents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField()),
                ("organization_id", models.UUIDField()),
                ("consent_type", models.TextField()),
                ("consent_category", models.TextField()),
                ("granted", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("consent_version", models.TextField(blank=True, null=True)),
                ("consent_text", models.TextField(blank=True, null=True)),
                ("consent_method", models.TextField(blank=True, null=True)),
                ("ip_address", models.TextField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("witnessed_by", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("requires_renewal", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField()),
                ("created_by", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MemberConsents",
                "db_table": "member_consents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberContactPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(unique=True)),
                ("organization_id", models.UUIDField()),
                ("preferred_contact_method", models.TextField(default="email")),
                (
                    "preferred_language",
                    models.TextField(blank=True, default="en", null=True),
                ),
                ("email_opt_in", models.BooleanField(default=False)),
                ("sms_opt_in", models.BooleanField(default=False)),
                ("phone_opt_in", models.BooleanField(default=False)),
                ("mail_opt_in", models.BooleanField(default=False)),
                (
                    "notification_preferences",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "best_contact_times",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("alternative_email", models.TextField(blank=True, null=True)),
                ("alternative_phone", models.TextField(blank=True, null=True)),
                ("emergency_contact_name", models.TextField(blank=True, null=True)),
                ("emergency_contact_phone", models.TextField(blank=True, null=True)),
                ("emergency_contact_relation", models.TextField(blank=True, null=True)),
                ("accessibility_needs", models.TextField(blank=True, null=True)),
                ("interpreter_required", models.BooleanField(default=False)),
                ("interpreter_language", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("last_modified_by", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MemberContactPreferences",
                "db_table": "member_contact_preferences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberEmploymentDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(unique=True)),
                ("organization_id", models.UUIDField()),
                ("classification", models.TextField()),
                ("job_title", models.TextField(blank=True, null=True)),
                ("job_code", models.TextField(blank=True, null=True)),
                ("pay_grade", models.TextField(blank=True, null=True)),
                ("work_location_id", models.UUIDField(blank=True, null=True)),
                ("department", models.TextField(blank=True, null=True)),
                ("division", models.TextField(blank=True, null=True)),
                ("cost_center", models.TextField(blank=True, null=True)),
                ("seniority_date", models.DateTimeField(blank=True, null=True)),
                ("seniority_years", models.IntegerField(blank=True, null=True)),
                ("seniority_points", models.IntegerField(blank=True, null=True)),
                ("shift_type", models.TextField(blank=True, null=True)),
                ("shift_start", models.TextField(blank=True, null=True)),
                ("shift_end", models.TextField(blank=True, null=True)),
                ("work_days", models.JSONField(blank=True, default=dict, null=True)),
                ("hours_per_week", models.IntegerField(blank=True, null=True)),
                ("supervisor_name", models.TextField(blank=True, null=True)),
                ("supervisor_id", models.UUIDField(blank=True, null=True)),
                ("supervisor_contact", models.TextField(blank=True, null=True)),
                ("employment_status", models.TextField(default="active")),
                ("status_effective_date", models.DateTimeField(blank=True, null=True)),
                ("status_reason", models.TextField(blank=True, null=True)),
                ("expected_return_date", models.DateTimeField(blank=True, null=True)),
                ("benefits_eligible", models.BooleanField(default=False)),
                (
                    "benefits_enrollment_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("pension_plan_enrolled", models.BooleanField(default=False)),
                ("probation_end_date", models.DateTimeField(blank=True, null=True)),
                ("is_probationary", models.BooleanField(default=False)),
                ("steward", models.BooleanField(default=False)),
                ("officer", models.BooleanField(default=False)),
                ("committee_member", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("last_modified_by", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MemberEmploymentDetails",
                "db_table": "member_employment_details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberHistoryEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField()),
                ("organization_id", models.UUIDField()),
                ("event_type", models.TextField()),
                ("event_category", models.TextField()),
                ("event_date", models.DateTimeField()),
                ("event_title", models.TextField()),
                ("event_description", models.TextField(blank=True, null=True)),
                ("event_data", models.JSONField(blank=True, default=dict, null=True)),
                ("actor_id", models.TextField(blank=True, null=True)),
                ("actor_name", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("visible_to_member", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField()),
                ("created_by", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MemberHistoryEvents",
                "db_table": "member_history_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OauthProviders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "OauthProviders",
                "db_table": "oauth_providers",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSharingGrants",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grantor_org_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OrganizationSharingGrants",
                "db_table": "organization_sharing_grants",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSharingSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OrganizationSharingSettings",
                "db_table": "organization_sharing_settings",
            },
        ),
        migrations.CreateModel(
            name="PendingProfiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.TextField(unique=True)),
                ("token", models.TextField(blank=True, null=True)),
                ("membership", models.TextField(default="pro")),
                (
                    "payment_provider",
                    models.TextField(blank=True, default="whop", null=True),
                ),
                ("whop_user_id", models.TextField(blank=True, null=True)),
                ("whop_membership_id", models.TextField(blank=True, null=True)),
                ("plan_duration", models.TextField(blank=True, null=True)),
                ("billing_cycle_start", models.DateTimeField(blank=True, null=True)),
                ("billing_cycle_end", models.DateTimeField(blank=True, null=True)),
                ("next_credit_renewal", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_credits",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("used_credits", models.IntegerField(blank=True, default=0, null=True)),
                ("claimed", models.BooleanField(default=False)),
                ("claimed_by_user_id", models.TextField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PendingProfiles",
                "db_table": "pending_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.TextField()),
                ("email", models.TextField(blank=True, null=True)),
                (
                    "membership",
                    models.CharField(
                        choices=[("free", "Free"), ("pro", "Pro")],
                        default="free",
                        max_length=14,
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[("stripe", "Stripe"), ("whop", "Whop")],
                        default="whop",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("stripe_customer_id", models.TextField(blank=True, null=True)),
                ("stripe_subscription_id", models.TextField(blank=True, null=True)),
                ("whop_user_id", models.TextField(blank=True, null=True)),
                (
                    "whop_membership_id",
                    models.CharField(
                        blank=True,
                        choices=[("free", "Free"), ("pro", "Pro")],
                        max_length=14,
                        null=True,
                    ),
                ),
                ("plan_duration", models.TextField(blank=True, null=True)),
                ("billing_cycle_start", models.DateTimeField(blank=True, null=True)),
                ("billing_cycle_end", models.DateTimeField(blank=True, null=True)),
                ("next_credit_renewal", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_credits",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("used_credits", models.IntegerField(blank=True, default=0, null=True)),
                ("status", models.TextField(blank=True, default="active", null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Profiles",
                "db_table": "profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserSessions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "UserSessions",
                "db_table": "user_sessions",
            },
        ),
        migrations.CreateModel(
            name="UserUuidMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("clerk_user_id", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UserUuidMapping",
                "db_table": "user_uuid_mapping",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("slug", models.TextField(unique=True)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("short_name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("congress", "Congress"),
                            ("federation", "Federation"),
                            ("union", "Union"),
                            ("local", "Local"),
                            ("region", "Region"),
                            ("district", "District"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hierarchy_path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        default=list,
                        help_text="Array of ancestor organization IDs from root to this node",
                        size=None,
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        default=0,
                        help_text="Distance from root (0 = root organization)",
                    ),
                ),
                ("province_territory", models.TextField(blank=True, null=True)),
                (
                    "sectors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("healthcare", "Healthcare"),
                                ("education", "Education"),
                                ("public_service", "Public Service"),
                                ("trades", "Trades"),
                                ("manufacturing", "Manufacturing"),
                                ("transportation", "Transportation"),
                                ("retail", "Retail"),
                                ("hospitality", "Hospitality"),
                                ("technology", "Technology"),
                                ("construction", "Construction"),
                                ("utilities", "Utilities"),
                                ("telecommunications", "Telecommunications"),
                                ("financial_services", "Financial Services"),
                                ("agriculture", "Agriculture"),
                                ("arts_culture", "Arts and Culture"),
                                ("other", "Other"),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                (
                    "address",
                    models.JSONField(
                        blank=True,
                        help_text="Format: {street, unit, city, province, postal_code, country}",
                        null=True,
                    ),
                ),
                (
                    "clc_affiliated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether affiliated with Canadian Labour Congress",
                    ),
                ),
                ("affiliation_date", models.DateField(blank=True, null=True)),
                ("charter_number", models.TextField(blank=True, null=True)),
                ("member_count", models.IntegerField(default=0)),
                ("active_member_count", models.IntegerField(default=0)),
                (
                    "last_member_count_update",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_tier", models.TextField(blank=True, null=True)),
                ("billing_contact_id", models.UUIDField(blank=True, null=True)),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text="Flexible config: {perCapitaRate, remittanceDay, fiscalYearEnd, customFields}",
                    ),
                ),
                (
                    "features_enabled",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "legacy_tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Original tenant_id from legacy system",
                        null=True,
                    ),
                ),
                (
                    "clc_affiliate_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "per_capita_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default per-capita rate for remittances",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "remittance_day",
                    models.IntegerField(
                        default=15, help_text="Day of month for remittances (1-31)"
                    ),
                ),
                ("last_remittance_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fiscal_year_end",
                    models.DateField(blank=True, help_text="e.g., March 31", null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="children",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationRelationships",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("affiliate", "Affiliate"),
                            ("federation", "Federation"),
                            ("local", "Local"),
                            ("chapter", "Chapter"),
                            ("region", "Region"),
                            ("district", "District"),
                            ("joint_council", "Joint Council"),
                            ("merged_from", "Merged From"),
                            ("split_from", "Split From"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                (
                    "child_org",
                    models.ForeignKey(
                        db_column="child_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relationships",
                        to="auth_core.organizations",
                    ),
                ),
                (
                    "parent_org",
                    models.ForeignKey(
                        db_column="parent_org_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_relationships",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Relationship",
                "verbose_name_plural": "Organization Relationships",
                "db_table": "organization_relationships",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField()),
                ("role", models.TextField()),
                ("status", models.TextField()),
                ("membership_number", models.TextField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "member_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_member", "Full Member"),
                            ("associate", "Associate"),
                            ("honorary", "Honorary"),
                            ("retired", "Retired"),
                        ],
                        max_length=21,
                        null=True,
                    ),
                ),
                ("exempt_from_per_capita", models.BooleanField(default=False)),
                ("exemption_reason", models.TextField(blank=True, null=True)),
                (
                    "exemption_approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_members_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrganizationMembers",
                "db_table": "organization_members",
            },
        ),
        migrations.CreateModel(
            name="MfaConfigurations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_configurations_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "MfaConfigurations",
                "db_table": "mfa_configurations",
            },
        ),
        migrations.CreateModel(
            name="OrganizationUsers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_user_id",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_users_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrganizationUsers",
                "db_table": "organization_users",
            },
        ),
        migrations.CreateModel(
            name="ScimConfigurations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scim_configurations_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "ScimConfigurations",
                "db_table": "scim_configurations",
            },
        ),
        migrations.CreateModel(
            name="ScimEventsLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scim_events_log_config_set",
                        to="auth_core.scimconfigurations",
                    ),
                ),
            ],
            options={
                "verbose_name": "ScimEventsLog",
                "db_table": "scim_events_log",
            },
        ),
        migrations.CreateModel(
            name="SsoProviders",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_providers_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "SsoProviders",
                "db_table": "sso_providers",
            },
        ),
        migrations.CreateModel(
            name="SsoSessions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_sessions_provider_set",
                        to="auth_core.ssoproviders",
                    ),
                ),
            ],
            options={
                "verbose_name": "SsoSessions",
                "db_table": "sso_sessions",
            },
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(fields=["parent"], name="idx_org_parent"),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(fields=["organization_type"], name="idx_org_type"),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(fields=["slug"], name="idx_org_slug"),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(
                fields=["hierarchy_level"], name="idx_org_hierarchy_level"
            ),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(fields=["status"], name="idx_org_status"),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(
                fields=["clc_affiliated"], name="idx_org_clc_affiliated"
            ),
        ),
        migrations.AddIndex(
            model_name="organizations",
            index=models.Index(
                fields=["legacy_tenant_id"], name="idx_org_legacy_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationrelationships",
            index=models.Index(
                fields=["parent_org"], name="idx_org_relationships_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationrelationships",
            index=models.Index(
                fields=["child_org"], name="idx_org_relationships_child"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationrelationships",
            index=models.Index(
                fields=["relationship_type"], name="idx_org_relationships_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationrelationships",
            constraint=models.UniqueConstraint(
                fields=(
                    "parent_org",
                    "child_org",
                    "relationship_type",
                    "effective_date",
                ),
                name="unique_org_relationship",
            ),
        ),
    ]
