# Generated by Django 5.1.15 on 2026-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='clerk_organization_id',
            field=models.TextField(blank=True, db_index=True, help_text='Clerk organization ID (e.g. org_2abc...) — set by webhook on organization.created', null=True, unique=True),
        ),
    ]
