"""
Django models for ai_core app.
Auto-generated by Nzila Code Generator — 2026-02-17

DO NOT EDIT manually unless you know what you're doing.
Re-run the generator to overwrite.
"""
import uuid
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField

try:
    from pgvector.django import VectorField
except ImportError:
    VectorField = None  # pgvector not installed


class BaseModel(models.Model):
    """Abstract base with standard audit fields."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OrganizationModel(BaseModel):
    """Abstract base for multi-organization models."""
    organization = models.ForeignKey(
        'auth_core.Organizations',
        on_delete=models.CASCADE,
        related_name='%(class)ss'
    )

    class Meta:
        abstract = True



class AbTests(BaseModel):
    """Migrated from drizzle: ab-testing-schema.ts"""
    name = models.TextField()
    description = models.TextField()
    type = models.TextField()
    status = models.TextField(default='draft')
    organization = models.ForeignKey('auth_core.Organizations', on_delete=models.CASCADE, related_name='ab_tests_organization_set', null=True, blank=True)

    class Meta:
        db_table = 'ab_tests'
        verbose_name = 'AbTests'

    def __str__(self):
        return str(self.name)

class AbTestVariants(BaseModel):
    """Migrated from drizzle: ab-testing-schema.ts"""
    test_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'ab_test_variants'
        verbose_name = 'AbTestVariants'

class AbTestAssignments(BaseModel):
    """Migrated from drizzle: ab-testing-schema.ts"""
    test_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'ab_test_assignments'
        verbose_name = 'AbTestAssignments'

class AbTestEvents(BaseModel):
    """Migrated from drizzle: ab-testing-schema.ts"""
    test_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'ab_test_events'
        verbose_name = 'AbTestEvents'

class AccessibilityAudits(BaseModel):
    """Migrated from drizzle: accessibility-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'accessibility_audits'
        verbose_name = 'AccessibilityAudits'

class AccessibilityIssues(BaseModel):
    """Migrated from drizzle: accessibility-schema.ts"""
    audit_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'accessibility_issues'
        verbose_name = 'AccessibilityIssues'

class WcagSuccessCriteria(BaseModel):
    """Migrated from drizzle: accessibility-schema.ts"""
    criteria_number = models.TextField(unique=True)
    criteria_title = models.TextField()
    criteria_description = models.TextField()
    level = models.TextField()
    wcag_version = models.TextField(default="2.2")
    principle = models.TextField()
    guideline = models.TextField()
    understanding_url = models.TextField(null=True, blank=True)
    how_to_meet_url = models.TextField(null=True, blank=True)
    testing_procedure = models.TextField(null=True, blank=True)
    common_failures = models.JSONField(default=dict, null=True, blank=True)
    sufficient_techniques = models.JSONField(default=dict, null=True, blank=True)
    keywords = models.JSONField(default=dict, null=True, blank=True)

    class Meta:
        db_table = 'wcag_success_criteria'
        verbose_name = 'WcagSuccessCriteria'
        ordering = ['-created_at']

class AccessibilityTestSuites(BaseModel):
    """Migrated from drizzle: accessibility-schema.ts"""
    organization = models.ForeignKey('auth_core.Organizations', on_delete=models.CASCADE, related_name='accessibility_test_suites_organization_set', null=True, blank=True)

    class Meta:
        db_table = 'accessibility_test_suites'
        verbose_name = 'AccessibilityTestSuites'

class AccessibilityUserTesting(BaseModel):
    """Migrated from drizzle: accessibility-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'accessibility_user_testing'
        verbose_name = 'AccessibilityUserTesting'

class ChatSessions(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    user_id = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'chat_sessions'
        verbose_name = 'ChatSessions'

class ChatMessages(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    session_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'chat_messages'
        verbose_name = 'ChatMessages'

class KnowledgeBase(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'knowledge_base'
        verbose_name = 'KnowledgeBase'

class ChatbotSuggestions(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'chatbot_suggestions'
        verbose_name = 'ChatbotSuggestions'

class ChatbotAnalytics(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'chatbot_analytics'
        verbose_name = 'ChatbotAnalytics'

class AiSafetyFilters(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    input = models.TextField()
    output = models.TextField(null=True, blank=True)
    flagged = models.BooleanField(default=False)
    flagged_categories = models.JSONField(default=dict, null=True, blank=True)
    confidence_scores = models.JSONField(default=dict, null=True, blank=True)
    action = models.TextField()
    reason = models.TextField(null=True, blank=True)
    session = models.ForeignKey('ChatSessions', on_delete=models.CASCADE, related_name='ai_safety_filters_session_set', null=True, blank=True)
    message = models.ForeignKey('ChatMessages', on_delete=models.CASCADE, related_name='ai_safety_filters_message_set', null=True, blank=True)
    created_at = models.DateTimeField()

    class Meta:
        db_table = 'ai_safety_filters'
        verbose_name = 'AiSafetyFilters'
        ordering = ['-created_at']

class AiUsageMetrics(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'ai_usage_metrics'
        verbose_name = 'AiUsageMetrics'

class AiRateLimits(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'ai_rate_limits'
        verbose_name = 'AiRateLimits'

class AiBudgets(BaseModel):
    """Migrated from drizzle: ai-chatbot-schema.ts"""
    organization_id = models.UUIDField(null=True, blank=True)

    class Meta:
        db_table = 'ai_budgets'
        verbose_name = 'AiBudgets'

class MlPredictions(BaseModel):
    """Migrated from drizzle: analytics.ts"""
    organization = models.ForeignKey('auth_core.Organizations', on_delete=models.CASCADE, related_name='ml_predictions_organization_set')

    class Meta:
        db_table = 'ml_predictions'
        verbose_name = 'MlPredictions'

class ModelMetadata(BaseModel):
    """Migrated from drizzle: predictions.ts"""
    organization = models.ForeignKey('auth_core.Organizations', on_delete=models.CASCADE, related_name='model_metadata_organization_set')

    class Meta:
        db_table = 'model_metadata'
        verbose_name = 'ModelMetadata'
