# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArbitrationDecisions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ArbitrationDecisions",
                "db_table": "arbitration_decisions",
            },
        ),
        migrations.CreateModel(
            name="ArbitrationPrecedents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ArbitrationPrecedents",
                "db_table": "arbitration_precedents",
            },
        ),
        migrations.CreateModel(
            name="ArbitratorProfiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ArbitratorProfiles",
                "db_table": "arbitrator_profiles",
            },
        ),
        migrations.CreateModel(
            name="CbaClauses",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "CbaClauses",
                "db_table": "cba_clauses",
            },
        ),
        migrations.CreateModel(
            name="ClauseComparisons",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comparison_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ClauseComparisons",
                "db_table": "clause_comparisons",
            },
        ),
        migrations.CreateModel(
            name="ClauseComparisonsHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ClauseComparisonsHistory",
                "db_table": "clause_comparisons_history",
            },
        ),
        migrations.CreateModel(
            name="ClauseLibraryTags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clause_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ClauseLibraryTags",
                "db_table": "clause_library_tags",
            },
        ),
        migrations.CreateModel(
            name="CollectiveAgreements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("cba_number", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "CollectiveAgreements",
                "db_table": "collective_agreements",
            },
        ),
        migrations.CreateModel(
            name="PrecedentCitations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("precedent_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PrecedentCitations",
                "db_table": "precedent_citations",
            },
        ),
        migrations.CreateModel(
            name="PrecedentTags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("precedent_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PrecedentTags",
                "db_table": "precedent_tags",
            },
        ),
        migrations.CreateModel(
            name="SharedClauseLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SharedClauseLibrary",
                "db_table": "shared_clause_library",
            },
        ),
        migrations.CreateModel(
            name="CbaFootnotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cba_footnotes_source_clause_set",
                        to="bargaining.cbaclauses",
                    ),
                ),
            ],
            options={
                "verbose_name": "CbaFootnotes",
                "db_table": "cba_footnotes",
            },
        ),
        migrations.CreateModel(
            name="CbaVersionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cba_version_history_cba_set",
                        to="bargaining.collectiveagreements",
                    ),
                ),
            ],
            options={
                "verbose_name": "CbaVersionHistory",
                "db_table": "cba_version_history",
            },
        ),
        migrations.CreateModel(
            name="CbaContacts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cba_contacts_cba_set",
                        to="bargaining.collectiveagreements",
                    ),
                ),
            ],
            options={
                "verbose_name": "CbaContacts",
                "db_table": "cba_contacts",
            },
        ),
        migrations.AddField(
            model_name="cbaclauses",
            name="cba",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cba_clauses_cba_set",
                to="bargaining.collectiveagreements",
            ),
        ),
        migrations.CreateModel(
            name="BenefitComparisons",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_comparisons_cba_set",
                        to="bargaining.collectiveagreements",
                    ),
                ),
            ],
            options={
                "verbose_name": "BenefitComparisons",
                "db_table": "benefit_comparisons",
            },
        ),
        migrations.CreateModel(
            name="BargainingNotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargaining_notes_cba_set",
                        to="bargaining.collectiveagreements",
                    ),
                ),
            ],
            options={
                "verbose_name": "BargainingNotes",
                "db_table": "bargaining_notes",
            },
        ),
        migrations.CreateModel(
            name="Negotiations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "expiring_cba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations_expiring_cba_set",
                        to="bargaining.collectiveagreements",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negotiations",
                "db_table": "negotiations",
            },
        ),
        migrations.CreateModel(
            name="BargainingTeamMembers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargaining_team_members_negotiation_set",
                        to="bargaining.negotiations",
                    ),
                ),
            ],
            options={
                "verbose_name": "BargainingTeamMembers",
                "db_table": "bargaining_team_members",
            },
        ),
        migrations.CreateModel(
            name="BargainingProposals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargaining_proposals_negotiation_set",
                        to="bargaining.negotiations",
                    ),
                ),
            ],
            options={
                "verbose_name": "BargainingProposals",
                "db_table": "bargaining_proposals",
            },
        ),
        migrations.CreateModel(
            name="NegotiationSessions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiation_sessions_negotiation_set",
                        to="bargaining.negotiations",
                    ),
                ),
            ],
            options={
                "verbose_name": "NegotiationSessions",
                "db_table": "negotiation_sessions",
            },
        ),
        migrations.CreateModel(
            name="TentativeAgreements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "negotiation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentative_agreements_negotiation_set",
                        to="bargaining.negotiations",
                    ),
                ),
            ],
            options={
                "verbose_name": "TentativeAgreements",
                "db_table": "tentative_agreements",
            },
        ),
        migrations.CreateModel(
            name="WageProgressions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wage_progressions_cba_set",
                        to="bargaining.collectiveagreements",
                    ),
                ),
            ],
            options={
                "verbose_name": "WageProgressions",
                "db_table": "wage_progressions",
            },
        ),
    ]
