"""
URL configuration for auth_core app.
Auto-generated by Nzila Code Generator — 2026-02-17
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'organizations', views.OrganizationsViewSet)
router.register(r'profiles', views.ProfilesViewSet)
router.register(r'roles', views.RolesViewSet)
router.register(r'permissions', views.PermissionsViewSet)
router.register(r'role-permissions', views.RolePermissionsViewSet)
router.register(r'user-roles', views.UserRolesViewSet)
router.register(r'audit-logs', views.AuditLogsViewSet)

app_name = 'auth_core'

urlpatterns = [
    path('', include(router.urls)),
    # Clerk authentication endpoints
    path('me/', views.me, name='me'),
    path('webhooks/clerk/', views.clerk_webhook, name='clerk_webhook'),
    path('health/', views.health_check, name='health_check'),
]