export { IntegrationDispatcher, type DispatcherPorts, type DispatcherOptions } from './dispatcher'
export { withRetry, computeDelay, shouldRetry, DEFAULT_RETRY_OPTIONS, type RetryOptions } from './retry'
export { checkAllIntegrations, type HealthCheckerPorts, type AggregateHealthResult } from './health'
export { CircuitBreaker, DEFAULT_CIRCUIT_BREAKER_CONFIG, type CircuitBreakerConfig, type CircuitBreakerPorts, type CircuitCheckResult, type CircuitRecordResult } from './circuitBreaker'
export { MetricsCollector, computePercentile, type MetricsCollectorPorts, type DeliveryMetricEvent } from './metrics'
export { parseRateLimitInfo, parseSlackRateLimit, parseHubSpotRateLimit, parseTeamsRateLimit, parseGenericRateLimit, type RateLimitParser } from './rateLimitParser'
export { ChaosSimulator, CHAOS_SCENARIOS, isChaosAllowed, type ChaosConfig, type ChaosScenario, type ChaosPorts } from './chaos'
export { SloComputer, type SloComputerPorts, type SloResult } from './slo'
export { ResilientDispatcher, type ResilientDispatcherPorts, type ResilientDispatcherOptions } from './resilientAdapter'

// PR4: Integration reliability hardening
export { withTimeout, getTimeoutMs, TimeoutError, DEFAULT_TIMEOUT_CONFIG, type TimeoutConfig } from './timeout'
export { createValidatedAdapter, validateSendRequest, type ValidationError, type ValidationResult } from './adapter-validator'
export { executeWithClassifiedRetry, DEFAULT_CLASSIFIED_RETRY_CONFIG, type ClassifiedRetryConfig, type ClassifiedRetryResult } from './classified-retry'
export { recordIntegrationTelemetry, recordSendTelemetry, type IntegrationTelemetryEvent, type TelemetryBridgePorts } from './telemetry-bridge'
export { MockAdapter, createMockAdapter, type MockAdapterConfig, type RecordedCall } from './mock-adapter'
