name: CD — Deploy to Staging

on:
  push:
    branches: [develop]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build -t ${{ vars.ACR_LOGIN_SERVER }}/backend:${{ github.sha }} backend/
          docker push ${{ vars.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}
      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ vars.CONTAINER_APP_NAME }}-backend
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          imageToDeploy: ${{ vars.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}

  deploy-frontend:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build -t ${{ vars.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} frontend/
          docker push ${{ vars.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ${{ vars.CONTAINER_APP_NAME }}-frontend
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          imageToDeploy: ${{ vars.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
