# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArmsLengthVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.UUIDField(unique=True)),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ArmsLengthVerification",
                "db_table": "arms_length_verification",
            },
        ),
        migrations.CreateModel(
            name="BandCouncilConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("band_council_id", models.UUIDField()),
                (
                    "consent_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "BandCouncilConsent",
                "db_table": "band_council_consent",
            },
        ),
        migrations.CreateModel(
            name="BandCouncils",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("band_name", models.TextField()),
                (
                    "band_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "BandCouncils",
                "db_table": "band_councils",
            },
        ),
        migrations.CreateModel(
            name="BlindTrustRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "BlindTrustRegistry",
                "db_table": "blind_trust_registry",
            },
        ),
        migrations.CreateModel(
            name="BreakGlassSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "BreakGlassSystem",
                "db_table": "break_glass_system",
            },
        ),
        migrations.CreateModel(
            name="CertificationAlerts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certification_id", models.UUIDField()),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "CertificationAlerts",
                "db_table": "certification_alerts",
            },
        ),
        migrations.CreateModel(
            name="CertificationAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CertificationAuditLog",
                "db_table": "certification_audit_log",
            },
        ),
        migrations.CreateModel(
            name="CertificationComplianceReports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField()),
                (
                    "report_period",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CertificationComplianceReports",
                "db_table": "certification_compliance_reports",
            },
        ),
        migrations.CreateModel(
            name="CertificationTypes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certification_name", models.TextField()),
                (
                    "certification_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CertificationTypes",
                "db_table": "certification_types",
            },
        ),
        migrations.CreateModel(
            name="ConflictAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ConflictAuditLog",
                "db_table": "conflict_audit_log",
            },
        ),
        migrations.CreateModel(
            name="ConflictDisclosures",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ConflictDisclosures",
                "db_table": "conflict_disclosures",
            },
        ),
        migrations.CreateModel(
            name="ConflictOfInterestPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_enabled", models.BooleanField(default=False)),
                ("blind_trust_required", models.BooleanField(default=False)),
                ("annual_disclosure_required", models.BooleanField(default=False)),
                (
                    "disclosure_deadline",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ConflictOfInterestPolicy",
                "db_table": "conflict_of_interest_policy",
            },
        ),
        migrations.CreateModel(
            name="ConflictReviewCommittee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ConflictReviewCommittee",
                "db_table": "conflict_review_committee",
            },
        ),
        migrations.CreateModel(
            name="ConflictTraining",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ConflictTraining",
                "db_table": "conflict_training",
            },
        ),
        migrations.CreateModel(
            name="ConsentRecords",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ConsentRecords",
                "db_table": "consent_records",
            },
        ),
        migrations.CreateModel(
            name="ContinuingEducation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ContinuingEducation",
                "db_table": "continuing_education",
            },
        ),
        migrations.CreateModel(
            name="CorrectiveActions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "action_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "CorrectiveActions",
                "db_table": "corrective_actions",
            },
        ),
        migrations.CreateModel(
            name="CouncilElections",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("election_year", models.IntegerField()),
                ("election_date", models.DateField()),
                ("positions_available", models.IntegerField()),
                ("candidates", models.JSONField(default=dict)),
                ("winners", models.JSONField(default=dict)),
                ("total_votes", models.IntegerField()),
                ("participation_rate", models.IntegerField(blank=True, null=True)),
                ("verified_by", models.TextField(blank=True, null=True)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("contested_results", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "CouncilElections",
                "db_table": "council_elections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataAnonymizationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DataAnonymizationLog",
                "db_table": "data_anonymization_log",
            },
        ),
        migrations.CreateModel(
            name="DataClassificationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_name", models.TextField()),
                ("policy_description", models.TextField(blank=True, null=True)),
                ("effective_date", models.DateTimeField()),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("enforce_strict_separation", models.BooleanField(default=False)),
                ("allow_bargaining_unit_roster", models.BooleanField(default=False)),
                ("allow_greivance_participation", models.BooleanField(default=False)),
                ("block_strike_plans", models.BooleanField(default=False)),
                ("block_membership_lists", models.BooleanField(default=False)),
                ("block_internal_discussions", models.BooleanField(default=False)),
                ("approved_by", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "DataClassificationPolicy",
                "db_table": "data_classification_policy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataClassificationRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_type", models.TextField()),
                ("classification_level", models.TextField()),
                ("accessible_by_employer", models.BooleanField(default=False)),
                ("accessible_by_union", models.BooleanField(default=False)),
                ("requires_justification", models.BooleanField(default=False)),
                ("data_description", models.TextField(blank=True, null=True)),
                ("legal_basis", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "DataClassificationRegistry",
                "db_table": "data_classification_registry",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataProcessingRecords",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DataProcessingRecords",
                "db_table": "data_processing_records",
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "DataRetentionPolicies",
                "db_table": "data_retention_policies",
            },
        ),
        migrations.CreateModel(
            name="DataSubjectAccessRequests",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "DataSubjectAccessRequests",
                "db_table": "data_subject_access_requests",
            },
        ),
        migrations.CreateModel(
            name="DisasterRecoveryDrills",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("drill_name", models.TextField()),
                ("drill_type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "DisasterRecoveryDrills",
                "db_table": "disaster_recovery_drills",
            },
        ),
        migrations.CreateModel(
            name="DsrRequests",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "DsrRequests",
                "db_table": "dsr_requests",
            },
        ),
        migrations.CreateModel(
            name="EmergencyDeclarations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "emergency_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "EmergencyDeclarations",
                "db_table": "emergency_declarations",
            },
        ),
        migrations.CreateModel(
            name="FirewallComplianceAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_date", models.DateTimeField()),
                ("audit_period", models.TextField()),
                ("total_access_attempts", models.TextField()),
                ("total_employer_attempts", models.TextField()),
                ("total_denied_access", models.TextField()),
                ("total_violations", models.TextField()),
                ("critical_violations", models.TextField()),
                ("compliance_rate", models.TextField()),
                (
                    "top_violated_data_types",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("recommended_actions", models.TextField(blank=True, null=True)),
                ("audited_by", models.TextField()),
                ("audit_report", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "FirewallComplianceAudit",
                "db_table": "firewall_compliance_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForeignWorkers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email", models.TextField(blank=True, null=True, unique=True)),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("work_permit_number", models.TextField(unique=True)),
                ("work_permit_expiry", models.DateTimeField()),
                ("country_of_origin", models.TextField()),
                ("employer_id", models.UUIDField()),
                ("position_title", models.TextField()),
                ("noc_code", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("immigration_pathway", models.TextField()),
                ("lmia_number", models.TextField(blank=True, null=True)),
                ("gss_category", models.TextField(blank=True, null=True)),
                ("requires_lmbp", models.BooleanField(default=False)),
                ("lmbp_letter_generated", models.BooleanField(default=False)),
                ("lmbp_letter_date", models.DateTimeField(blank=True, null=True)),
                (
                    "skills_transfer_plan",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("mentorship_start_date", models.DateTimeField(blank=True, null=True)),
                ("mentorship_end_date", models.DateTimeField(blank=True, null=True)),
                ("compliance_status", models.TextField(default="pending")),
                ("last_compliance_check", models.DateTimeField(blank=True, null=True)),
                ("compliance_notes", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ForeignWorkers",
                "db_table": "foreign_workers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GdprDataRequests",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "GdprDataRequests",
                "db_table": "gdpr_data_requests",
            },
        ),
        migrations.CreateModel(
            name="GeofenceEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "GeofenceEvents",
                "db_table": "geofence_events",
            },
        ),
        migrations.CreateModel(
            name="Geofences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "geofence_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Geofences",
                "db_table": "geofences",
            },
        ),
        migrations.CreateModel(
            name="GoldenShares",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("share_class", models.TextField(default="B")),
                ("certificate_number", models.TextField(unique=True)),
                ("issue_date", models.DateField()),
                ("holder_type", models.TextField(default="council")),
                ("council_members", models.JSONField(default=dict)),
                ("voting_power_reserved_matters", models.IntegerField(default=51)),
                ("voting_power_ordinary_matters", models.IntegerField(default=1)),
                ("redemption_value", models.IntegerField(default=1)),
                ("dividend_rights", models.BooleanField(default=False)),
                ("sunset_clause_active", models.BooleanField(default=False)),
                ("sunset_clause_duration", models.IntegerField(default=5)),
                ("consecutive_compliance_years", models.IntegerField(default=0)),
                ("sunset_triggered_date", models.DateField(blank=True, null=True)),
                ("conversion_date", models.DateField(blank=True, null=True)),
                ("status", models.TextField(default="active")),
                ("transferable", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "GoldenShares",
                "db_table": "golden_shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.TextField()),
                ("event_date", models.DateTimeField()),
                ("golden_share_id", models.UUIDField(blank=True, null=True)),
                ("reserved_matter_vote_id", models.UUIDField(blank=True, null=True)),
                ("mission_audit_id", models.UUIDField(blank=True, null=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("impact", models.TextField(blank=True, null=True)),
                ("impact_description", models.TextField(blank=True, null=True)),
                ("stakeholders", models.JSONField(blank=True, default=dict, null=True)),
                ("notifications_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "GovernanceEvents",
                "db_table": "governance_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GssApplications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("foreign_worker_id", models.UUIDField()),
                ("application_number", models.TextField(unique=True)),
                ("submission_date", models.DateTimeField()),
                ("gss_category", models.TextField()),
                ("expected_decision_date", models.DateTimeField()),
                ("actual_decision_date", models.DateTimeField(blank=True, null=True)),
                ("processing_days", models.IntegerField(blank=True, null=True)),
                ("met2_week_target", models.BooleanField(default=False)),
                ("status", models.TextField(default="submitted")),
                (
                    "decision_details",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("documents", models.JSONField(blank=True, default=dict, null=True)),
                ("employer_id", models.UUIDField()),
                (
                    "position_details",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "compliance_flags",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "GssApplications",
                "db_table": "gss_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HazardReports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "report_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "HazardReports",
                "db_table": "hazard_reports",
            },
        ),
        migrations.CreateModel(
            name="IndigenousDataAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "IndigenousDataAccessLog",
                "db_table": "indigenous_data_access_log",
            },
        ),
        migrations.CreateModel(
            name="IndigenousDataSharingAgreements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("band_council_id", models.UUIDField()),
                ("partner_name", models.TextField()),
                (
                    "partner_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "IndigenousDataSharingAgreements",
                "db_table": "indigenous_data_sharing_agreements",
            },
        ),
        migrations.CreateModel(
            name="IndigenousMemberData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "IndigenousMemberData",
                "db_table": "indigenous_member_data",
            },
        ),
        migrations.CreateModel(
            name="InjuryLogs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("log_number", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "InjuryLogs",
                "db_table": "injury_logs",
            },
        ),
        migrations.CreateModel(
            name="KeyHolderRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "KeyHolderRegistry",
                "db_table": "key_holder_registry",
            },
        ),
        migrations.CreateModel(
            name="LegalHolds",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "LegalHolds",
                "db_table": "legal_holds",
            },
        ),
        migrations.CreateModel(
            name="LicenseRenewals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("certification_id", models.UUIDField()),
                (
                    "renewal_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "LicenseRenewals",
                "db_table": "license_renewals",
            },
        ),
        migrations.CreateModel(
            name="LmbpComplianceAlerts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alert_type", models.TextField()),
                ("severity", models.TextField()),
                ("foreign_worker_id", models.UUIDField(blank=True, null=True)),
                ("employer_id", models.UUIDField(blank=True, null=True)),
                ("lmbp_letter_id", models.UUIDField(blank=True, null=True)),
                ("gss_application_id", models.UUIDField(blank=True, null=True)),
                ("mentorship_id", models.UUIDField(blank=True, null=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("recommended_action", models.TextField(blank=True, null=True)),
                ("triggered_at", models.DateTimeField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.TextField(default="open")),
                ("resolution", models.TextField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "LmbpComplianceAlerts",
                "db_table": "lmbp_compliance_alerts",
            },
        ),
        migrations.CreateModel(
            name="LmbpComplianceReports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lmbp_letter_id", models.UUIDField()),
                ("employer_id", models.UUIDField()),
                ("reporting_period_start", models.DateTimeField()),
                ("reporting_period_end", models.DateTimeField()),
                ("submitted_to_ircc", models.BooleanField(default=False)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("ircc_confirmation_number", models.TextField(blank=True, null=True)),
                ("commitment_progress", models.JSONField(default=dict)),
                ("total_foreign_workers", models.IntegerField()),
                ("total_mentorships", models.IntegerField()),
                ("mentorships_completed", models.IntegerField()),
                ("canadian_workers_hired", models.IntegerField()),
                (
                    "training_investment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "LmbpComplianceReports",
                "db_table": "lmbp_compliance_reports",
            },
        ),
        migrations.CreateModel(
            name="LmbpLetters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employer_id", models.UUIDField()),
                ("employer_name", models.TextField()),
                ("letter_number", models.TextField(unique=True)),
                ("generated_date", models.DateTimeField()),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("commitments", models.JSONField(default=dict)),
                ("foreign_worker_ids", models.JSONField(default=dict)),
                ("compliance_report_due", models.DateTimeField(blank=True, null=True)),
                ("last_compliance_report", models.DateTimeField(blank=True, null=True)),
                (
                    "compliance_status",
                    models.TextField(blank=True, default="active", null=True),
                ),
                ("letter_pdf_url", models.TextField(blank=True, null=True)),
                ("letter_pdf_hash", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "LmbpLetters",
                "db_table": "lmbp_letters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationDeletionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deletion_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "LocationDeletionLog",
                "db_table": "location_deletion_log",
            },
        ),
        migrations.CreateModel(
            name="LocationTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "LocationTracking",
                "db_table": "location_tracking",
            },
        ),
        migrations.CreateModel(
            name="LocationTrackingAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "LocationTrackingAudit",
                "db_table": "location_tracking_audit",
            },
        ),
        migrations.CreateModel(
            name="LocationTrackingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location_tracking_enabled", models.BooleanField(default=False)),
                (
                    "max_retention_hours",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "LocationTrackingConfig",
                "db_table": "location_tracking_config",
            },
        ),
        migrations.CreateModel(
            name="LrbAgreements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "LrbAgreements",
                "db_table": "lrb_agreements",
            },
        ),
        migrations.CreateModel(
            name="LrbEmployers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "LrbEmployers",
                "db_table": "lrb_employers",
            },
        ),
        migrations.CreateModel(
            name="LrbSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "LrbSyncLog",
                "db_table": "lrb_sync_log",
            },
        ),
        migrations.CreateModel(
            name="LrbUnions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("union_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "LrbUnions",
                "db_table": "lrb_unions",
            },
        ),
        migrations.CreateModel(
            name="Mentorships",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mentee_id", models.UUIDField()),
                ("mentee_name", models.TextField()),
                ("mentor_id", models.UUIDField()),
                ("mentor_name", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("actual_end_date", models.DateTimeField(blank=True, null=True)),
                ("skills_to_transfer", models.JSONField(default=dict)),
                (
                    "learning_objectives",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("meeting_frequency", models.TextField(blank=True, null=True)),
                (
                    "total_meetings",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("last_meeting_date", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_percentage",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("canadian_worker_trained", models.BooleanField(default=False)),
                ("knowledge_transfer_documented", models.BooleanField(default=False)),
                ("status", models.TextField(default="active")),
                ("status_reason", models.TextField(blank=True, null=True)),
                ("employer_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "Mentorships",
                "db_table": "mentorships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissionAudits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_year", models.IntegerField()),
                ("audit_period_start", models.DateField()),
                ("audit_period_end", models.DateField()),
                ("auditor_firm", models.TextField()),
                ("auditor_name", models.TextField()),
                ("auditor_certification", models.TextField(blank=True, null=True)),
                ("audit_date", models.DateField()),
                ("union_revenue_percent", models.IntegerField()),
                ("member_satisfaction_percent", models.IntegerField()),
                ("data_violations", models.IntegerField(default=0)),
                ("union_revenue_threshold", models.IntegerField(default=90)),
                ("member_satisfaction_threshold", models.IntegerField(default=80)),
                ("data_violations_threshold", models.IntegerField(default=0)),
                ("union_revenue_pass", models.BooleanField(default=False)),
                ("member_satisfaction_pass", models.BooleanField(default=False)),
                ("data_violations_pass", models.BooleanField(default=False)),
                ("overall_pass", models.BooleanField(default=False)),
                ("total_revenue", models.IntegerField(blank=True, null=True)),
                ("union_revenue", models.IntegerField(blank=True, null=True)),
                (
                    "member_survey_sample_size",
                    models.IntegerField(blank=True, null=True),
                ),
                ("member_survey_responses", models.IntegerField(blank=True, null=True)),
                (
                    "data_violation_details",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("auditor_opinion", models.TextField()),
                ("auditor_notes", models.TextField(blank=True, null=True)),
                (
                    "corrective_actions",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("impacts_consecutive_compliance", models.BooleanField(default=False)),
                (
                    "consecutive_years_after_audit",
                    models.IntegerField(blank=True, null=True),
                ),
                ("audit_report_pdf_url", models.TextField(blank=True, null=True)),
                (
                    "supporting_documents_urls",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
            ],
            options={
                "verbose_name": "MissionAudits",
                "db_table": "mission_audits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PciDssCardholderDataFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PciDssCardholderDataFlow",
                "db_table": "pci_dss_cardholder_data_flow",
            },
        ),
        migrations.CreateModel(
            name="PciDssEncryptionKeys",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PciDssEncryptionKeys",
                "db_table": "pci_dss_encryption_keys",
            },
        ),
        migrations.CreateModel(
            name="PciDssQuarterlyScans",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PciDssQuarterlyScans",
                "db_table": "pci_dss_quarterly_scans",
            },
        ),
        migrations.CreateModel(
            name="PciDssRequirements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assessment_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PciDssRequirements",
                "db_table": "pci_dss_requirements",
            },
        ),
        migrations.CreateModel(
            name="PciDssSaqAssessments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PciDssSaqAssessments",
                "db_table": "pci_dss_saq_assessments",
            },
        ),
        migrations.CreateModel(
            name="PolicyRules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "PolicyRules",
                "db_table": "policy_rules",
            },
        ),
        migrations.CreateModel(
            name="PpeEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "item_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "PpeEquipment",
                "db_table": "ppe_equipment",
            },
        ),
        migrations.CreateModel(
            name="PrivacyBreaches",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breach_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "PrivacyBreaches",
                "db_table": "privacy_breaches",
            },
        ),
        migrations.CreateModel(
            name="ProvincialConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ProvincialConsent",
                "db_table": "provincial_consent",
            },
        ),
        migrations.CreateModel(
            name="ProvincialDataHandling",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ProvincialDataHandling",
                "db_table": "provincial_data_handling",
            },
        ),
        migrations.CreateModel(
            name="ProvincialPrivacyConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("province", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "ProvincialPrivacyConfig",
                "db_table": "provincial_privacy_config",
            },
        ),
        migrations.CreateModel(
            name="RecoveryTimeObjectives",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system_component",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "RecoveryTimeObjectives",
                "db_table": "recovery_time_objectives",
            },
        ),
        migrations.CreateModel(
            name="RecusalTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "RecusalTracking",
                "db_table": "recusal_tracking",
            },
        ),
        migrations.CreateModel(
            name="ReservedMatterVotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("matter_type", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "proposed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "ReservedMatterVotes",
                "db_table": "reserved_matter_votes",
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "RetentionPolicies",
                "db_table": "retention_policies",
            },
        ),
        migrations.CreateModel(
            name="SafetyAudits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "audit_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "SafetyAudits",
                "db_table": "safety_audits",
            },
        ),
        migrations.CreateModel(
            name="SafetyCertifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "certification_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "SafetyCertifications",
                "db_table": "safety_certifications",
            },
        ),
        migrations.CreateModel(
            name="SafetyCommitteeMeetings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "meeting_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "SafetyCommitteeMeetings",
                "db_table": "safety_committee_meetings",
            },
        ),
        migrations.CreateModel(
            name="SafetyInspections",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "inspection_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "SafetyInspections",
                "db_table": "safety_inspections",
            },
        ),
        migrations.CreateModel(
            name="SafetyPolicies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "policy_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "SafetyPolicies",
                "db_table": "safety_policies",
            },
        ),
        migrations.CreateModel(
            name="SafetyTrainingRecords",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "record_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "SafetyTrainingRecords",
                "db_table": "safety_training_records",
            },
        ),
        migrations.CreateModel(
            name="StaffCertifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "StaffCertifications",
                "db_table": "staff_certifications",
            },
        ),
        migrations.CreateModel(
            name="SwissColdStorage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vault_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "SwissColdStorage",
                "db_table": "swiss_cold_storage",
            },
        ),
        migrations.CreateModel(
            name="TraditionalKnowledgeRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("band_council_id", models.UUIDField()),
                (
                    "knowledge_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "TraditionalKnowledgeRegistry",
                "db_table": "traditional_knowledge_registry",
            },
        ),
        migrations.CreateModel(
            name="UnionOnlyDataTags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resource_type", models.TextField()),
                ("resource_id", models.TextField()),
                ("resource_name", models.TextField(blank=True, null=True)),
                ("union_only_flag", models.BooleanField(default=False)),
                ("employer_access_blocked", models.BooleanField(default=False)),
                ("classification_level", models.TextField(default="union_only")),
                ("tagged_by", models.TextField()),
                ("tagged_at", models.DateTimeField()),
                ("tag_reason", models.TextField(blank=True, null=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "UnionOnlyDataTags",
                "db_table": "union_only_data_tags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserConsents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UserConsents",
                "db_table": "user_consents",
            },
        ),
        migrations.CreateModel(
            name="WorkplaceIncidents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                (
                    "incident_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "WorkplaceIncidents",
                "db_table": "workplace_incidents",
            },
        ),
        migrations.CreateModel(
            name="CookieConsents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cookie_consents_user_set",
                        to="auth_core.profiles",
                    ),
                ),
            ],
            options={
                "verbose_name": "CookieConsents",
                "db_table": "cookie_consents",
            },
        ),
        migrations.CreateModel(
            name="AccessJustificationRequests",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_date", models.DateTimeField()),
                ("requested_by", models.TextField()),
                ("requested_by_email", models.TextField()),
                ("requested_by_role", models.TextField()),
                ("data_type_requested", models.TextField()),
                ("justification", models.TextField()),
                ("business_purpose", models.TextField(blank=True, null=True)),
                ("request_status", models.TextField(default="pending")),
                ("reviewed_by", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_decision", models.TextField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("approval_expiry_date", models.DateTimeField(blank=True, null=True)),
                ("access_granted_at", models.DateTimeField(blank=True, null=True)),
                ("access_revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "data_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_justification_requests_data_type_set",
                        to="compliance.dataclassificationregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "AccessJustificationRequests",
                "db_table": "access_justification_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataResidencyConfigs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_residency_configs_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "DataResidencyConfigs",
                "db_table": "data_residency_configs",
            },
        ),
        migrations.CreateModel(
            name="DsrActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsr_activity_log_request_set",
                        to="compliance.dsrrequests",
                    ),
                ),
            ],
            options={
                "verbose_name": "DsrActivityLog",
                "db_table": "dsr_activity_log",
            },
        ),
        migrations.CreateModel(
            name="BreakGlassActivations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activation_initiated_at", models.DateTimeField()),
                ("activation_approved_at", models.DateTimeField(blank=True, null=True)),
                ("activation_reason", models.TextField()),
                (
                    "key_holder_ids",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "secret_shares",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("required_signatures", models.IntegerField(default=3)),
                ("signatures_received", models.IntegerField(default=0)),
                (
                    "signature1_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="break_glass_activations_emergency_set",
                        to="compliance.emergencydeclarations",
                    ),
                ),
            ],
            options={
                "verbose_name": "BreakGlassActivations",
                "db_table": "break_glass_activations",
            },
        ),
        migrations.CreateModel(
            name="EmployerAccessAttempts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_timestamp", models.DateTimeField()),
                ("user_id", models.TextField()),
                ("user_email", models.TextField()),
                ("user_role", models.TextField()),
                ("data_type_requested", models.TextField()),
                ("access_granted", models.BooleanField(default=False)),
                ("denial_reason", models.TextField(blank=True, null=True)),
                ("justification_provided", models.TextField(blank=True, null=True)),
                ("ip_address", models.TextField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.TextField(blank=True, null=True)),
                ("flagged_for_review", models.BooleanField(default=False)),
                ("reviewed_by", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                (
                    "data_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_access_attempts_data_type_set",
                        to="compliance.dataclassificationregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "EmployerAccessAttempts",
                "db_table": "employer_access_attempts",
            },
        ),
        migrations.CreateModel(
            name="FirewallAccessRules",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_name", models.TextField()),
                ("user_role", models.TextField()),
                ("access_permitted", models.BooleanField(default=False)),
                ("access_level", models.TextField(blank=True, null=True)),
                ("justification_required", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approver_role", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firewall_access_rules_data_type_set",
                        to="compliance.dataclassificationregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "FirewallAccessRules",
                "db_table": "firewall_access_rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirewallViolations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("violation_date", models.DateTimeField()),
                ("violation_type", models.TextField()),
                ("severity", models.TextField()),
                ("user_id", models.TextField()),
                ("user_email", models.TextField()),
                ("user_role", models.TextField()),
                ("data_type_accessed", models.TextField(blank=True, null=True)),
                ("violation_description", models.TextField()),
                ("system_detected", models.BooleanField(default=False)),
                ("detected_by", models.TextField(blank=True, null=True)),
                ("incident_status", models.TextField(default="open")),
                ("investigated_by", models.TextField(blank=True, null=True)),
                ("investigation_notes", models.TextField(blank=True, null=True)),
                ("resolution_action", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "data_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firewall_violations_data_type_set",
                        to="compliance.dataclassificationregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "FirewallViolations",
                "db_table": "firewall_violations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyExceptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_exceptions_rule_set",
                        to="compliance.policyrules",
                    ),
                ),
            ],
            options={
                "verbose_name": "PolicyExceptions",
                "db_table": "policy_exceptions",
            },
        ),
        migrations.CreateModel(
            name="PolicyEvaluations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_evaluations_rule_set",
                        to="compliance.policyrules",
                    ),
                ),
            ],
            options={
                "verbose_name": "PolicyEvaluations",
                "db_table": "policy_evaluations",
            },
        ),
    ]
