# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Campaigns",
                "db_table": "campaigns",
            },
        ),
        migrations.CreateModel(
            name="CommunicationChannels",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CommunicationChannels",
                "db_table": "communication_channels",
            },
        ),
        migrations.CreateModel(
            name="CommunicationPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CommunicationPreferences",
                "db_table": "communication_preferences",
            },
        ),
        migrations.CreateModel(
            name="CommunicationPreferencesPhase4",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField()),
                ("organization_id", models.UUIDField()),
                (
                    "email_opt_in",
                    models.TextField(blank=True, default="true", null=True),
                ),
                ("sms_opt_in", models.TextField(blank=True, default="true", null=True)),
                ("quiet_hours_start", models.TextField(blank=True, null=True)),
                ("quiet_hours_end", models.TextField(blank=True, null=True)),
                (
                    "timezone",
                    models.TextField(blank=True, default="America/Toronto", null=True),
                ),
            ],
            options={
                "verbose_name": "CommunicationPreferencesPhase4",
                "db_table": "communication_preferences_phase4",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InAppNotifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "InAppNotifications",
                "db_table": "in_app_notifications",
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MessageLog",
                "db_table": "message_log",
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Messages",
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="MessageTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MessageTemplates",
                "db_table": "message_templates",
            },
        ),
        migrations.CreateModel(
            name="MessageThreads",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.TextField()),
                ("member_id", models.TextField()),
                ("staff_id", models.TextField(blank=True, null=True)),
                ("organization_id", models.UUIDField()),
                ("status", models.TextField(default="open")),
                ("priority", models.TextField(blank=True, default="normal", null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "MessageThreads",
                "db_table": "message_threads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MobileAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "MobileAnalytics",
                "db_table": "mobile_analytics",
            },
        ),
        migrations.CreateModel(
            name="MobileDevices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "MobileDevices",
                "db_table": "mobile_devices",
            },
        ),
        migrations.CreateModel(
            name="NewsletterCampaigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NewsletterCampaigns",
                "db_table": "newsletter_campaigns",
            },
        ),
        migrations.CreateModel(
            name="NewsletterDistributionLists",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NewsletterDistributionLists",
                "db_table": "newsletter_distribution_lists",
            },
        ),
        migrations.CreateModel(
            name="NewsletterEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NewsletterEngagement",
                "db_table": "newsletter_engagement",
            },
        ),
        migrations.CreateModel(
            name="NewsletterListSubscribers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("list_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NewsletterListSubscribers",
                "db_table": "newsletter_list_subscribers",
            },
        ),
        migrations.CreateModel(
            name="NewsletterRecipients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NewsletterRecipients",
                "db_table": "newsletter_recipients",
            },
        ),
        migrations.CreateModel(
            name="NewsletterTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NewsletterTemplates",
                "db_table": "newsletter_templates",
            },
        ),
        migrations.CreateModel(
            name="NotificationBounces",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NotificationBounces",
                "db_table": "notification_bounces",
            },
        ),
        migrations.CreateModel(
            name="NotificationDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NotificationDeliveryLog",
                "db_table": "notification_delivery_log",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remittance_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField()),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "NotificationLog",
                "db_table": "notification_log",
            },
        ),
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NotificationQueue",
                "db_table": "notification_queue",
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Notifications",
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NotificationTemplates",
                "db_table": "notification_templates",
            },
        ),
        migrations.CreateModel(
            name="NotificationTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField()),
                ("recipient_id", models.UUIDField(blank=True, null=True)),
                ("type", models.TextField()),
                ("status", models.TextField(default="pending")),
                ("priority", models.TextField(default="normal")),
                ("subject", models.TextField(blank=True, null=True)),
                ("body", models.TextField()),
                ("html_body", models.TextField(blank=True, null=True)),
                ("template_id", models.TextField(blank=True, null=True)),
                (
                    "template_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("provider_id", models.TextField(blank=True, null=True)),
                ("external_message_id", models.TextField(blank=True, null=True)),
                ("action_url", models.TextField(blank=True, null=True)),
                ("action_label", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                (
                    "failure_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "NotificationTracking",
                "db_table": "notification_tracking",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushDeliveries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notification_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PushDeliveries",
                "db_table": "push_deliveries",
            },
        ),
        migrations.CreateModel(
            name="PushDevices",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PushDevices",
                "db_table": "push_devices",
            },
        ),
        migrations.CreateModel(
            name="PushNotifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PushNotifications",
                "db_table": "push_notifications",
            },
        ),
        migrations.CreateModel(
            name="PushNotificationTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PushNotificationTemplates",
                "db_table": "push_notification_templates",
            },
        ),
        migrations.CreateModel(
            name="SmsCampaignRecipients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SmsCampaignRecipients",
                "db_table": "sms_campaign_recipients",
            },
        ),
        migrations.CreateModel(
            name="SmsCampaigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SmsCampaigns",
                "db_table": "sms_campaigns",
            },
        ),
        migrations.CreateModel(
            name="SmsConversations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SmsConversations",
                "db_table": "sms_conversations",
            },
        ),
        migrations.CreateModel(
            name="SmsMessages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SmsMessages",
                "db_table": "sms_messages",
            },
        ),
        migrations.CreateModel(
            name="SmsOptOuts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SmsOptOuts",
                "db_table": "sms_opt_outs",
            },
        ),
        migrations.CreateModel(
            name="SmsRateLimits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SmsRateLimits",
                "db_table": "sms_rate_limits",
            },
        ),
        migrations.CreateModel(
            name="SmsTemplates",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SmsTemplates",
                "db_table": "sms_templates",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField(unique=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "UserNotificationPreferences",
                "db_table": "user_notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="MessageReadReceipts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_read_receipts_message_set",
                        to="notifications.messages",
                    ),
                ),
            ],
            options={
                "verbose_name": "MessageReadReceipts",
                "db_table": "message_read_receipts",
            },
        ),
        migrations.CreateModel(
            name="MessageNotifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_notifications_message_set",
                        to="notifications.messages",
                    ),
                ),
            ],
            options={
                "verbose_name": "MessageNotifications",
                "db_table": "message_notifications",
            },
        ),
        migrations.AddField(
            model_name="messages",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_thread_set",
                to="notifications.messagethreads",
            ),
        ),
        migrations.CreateModel(
            name="MessageParticipants",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_participants_thread_set",
                        to="notifications.messagethreads",
                    ),
                ),
            ],
            options={
                "verbose_name": "MessageParticipants",
                "db_table": "message_participants",
            },
        ),
        migrations.CreateModel(
            name="MobileAppConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_app_config_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "MobileAppConfig",
                "db_table": "mobile_app_config",
            },
        ),
        migrations.CreateModel(
            name="MobileNotifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_notifications_device_set",
                        to="notifications.mobiledevices",
                    ),
                ),
            ],
            options={
                "verbose_name": "MobileNotifications",
                "db_table": "mobile_notifications",
            },
        ),
        migrations.CreateModel(
            name="MobileSyncQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_sync_queue_device_set",
                        to="notifications.mobiledevices",
                    ),
                ),
            ],
            options={
                "verbose_name": "MobileSyncQueue",
                "db_table": "mobile_sync_queue",
            },
        ),
        migrations.CreateModel(
            name="NotificationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_history_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "NotificationHistory",
                "db_table": "notification_history",
            },
        ),
    ]
