"use client";

import { ShieldAlert, Info } from "lucide-react";

interface DecisionReviewBannerProps {
  pendingReview: number;
  criticalOpen: number;
}

export function DecisionReviewBanner({
  pendingReview,
  criticalOpen,
}: DecisionReviewBannerProps) {
  if (pendingReview === 0 && criticalOpen === 0) {
    return (
      <div className="rounded-lg border border-emerald-200 bg-emerald-50 dark:border-emerald-900/50 dark:bg-emerald-900/20 p-4 flex items-start gap-3">
        <Info className="h-5 w-5 text-emerald-600 dark:text-emerald-400 mt-0.5" />
        <div>
          <p className="text-sm font-medium text-emerald-800 dark:text-emerald-300">
            All decisions reviewed
          </p>
          <p className="text-xs text-emerald-700 dark:text-emerald-400 mt-0.5">
            No open decisions require attention. The Decision Layer is generating
            recommendations — all have been reviewed by a human approver.
          </p>
        </div>
      </div>
    );
  }

  const isCritical = criticalOpen > 0;

  return (
    <div
      className={`rounded-lg border p-4 flex items-start gap-3 ${
        isCritical
          ? "border-red-200 bg-red-50 dark:border-red-900/50 dark:bg-red-900/20"
          : "border-amber-200 bg-amber-50 dark:border-amber-900/50 dark:bg-amber-900/20"
      }`}
    >
      <ShieldAlert
        className={`h-5 w-5 mt-0.5 ${
          isCritical
            ? "text-red-600 dark:text-red-400"
            : "text-amber-600 dark:text-amber-400"
        }`}
      />
      <div>
        <p
          className={`text-sm font-medium ${
            isCritical
              ? "text-red-800 dark:text-red-300"
              : "text-amber-800 dark:text-amber-300"
          }`}
        >
          {criticalOpen > 0
            ? `${criticalOpen} critical decision${criticalOpen > 1 ? "s" : ""} require review`
            : `${pendingReview} decision${pendingReview > 1 ? "s" : ""} pending review`}
        </p>
        <p
          className={`text-xs mt-0.5 ${
            isCritical
              ? "text-red-700 dark:text-red-400"
              : "text-amber-700 dark:text-amber-400"
          }`}
        >
          These recommendations have been generated by the Decision Layer and are
          awaiting human review. No automatic action has been taken.
        </p>
      </div>
    </div>
  );
}
