# Generated by Django 5.1.4 on 2026-02-18 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbTestAssignments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AbTestAssignments",
                "db_table": "ab_test_assignments",
            },
        ),
        migrations.CreateModel(
            name="AbTestEvents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AbTestEvents",
                "db_table": "ab_test_events",
            },
        ),
        migrations.CreateModel(
            name="AbTestVariants",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AbTestVariants",
                "db_table": "ab_test_variants",
            },
        ),
        migrations.CreateModel(
            name="AccessibilityAudits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AccessibilityAudits",
                "db_table": "accessibility_audits",
            },
        ),
        migrations.CreateModel(
            name="AccessibilityIssues",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AccessibilityIssues",
                "db_table": "accessibility_issues",
            },
        ),
        migrations.CreateModel(
            name="AccessibilityUserTesting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AccessibilityUserTesting",
                "db_table": "accessibility_user_testing",
            },
        ),
        migrations.CreateModel(
            name="AiBudgets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AiBudgets",
                "db_table": "ai_budgets",
            },
        ),
        migrations.CreateModel(
            name="AiRateLimits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AiRateLimits",
                "db_table": "ai_rate_limits",
            },
        ),
        migrations.CreateModel(
            name="AiUsageMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AiUsageMetrics",
                "db_table": "ai_usage_metrics",
            },
        ),
        migrations.CreateModel(
            name="ChatbotAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ChatbotAnalytics",
                "db_table": "chatbot_analytics",
            },
        ),
        migrations.CreateModel(
            name="ChatbotSuggestions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ChatbotSuggestions",
                "db_table": "chatbot_suggestions",
            },
        ),
        migrations.CreateModel(
            name="ChatMessages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ChatMessages",
                "db_table": "chat_messages",
            },
        ),
        migrations.CreateModel(
            name="ChatSessions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ChatSessions",
                "db_table": "chat_sessions",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "KnowledgeBase",
                "db_table": "knowledge_base",
            },
        ),
        migrations.CreateModel(
            name="WcagSuccessCriteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("criteria_number", models.TextField(unique=True)),
                ("criteria_title", models.TextField()),
                ("criteria_description", models.TextField()),
                ("level", models.TextField()),
                ("wcag_version", models.TextField(default="2.2")),
                ("principle", models.TextField()),
                ("guideline", models.TextField()),
                ("understanding_url", models.TextField(blank=True, null=True)),
                ("how_to_meet_url", models.TextField(blank=True, null=True)),
                ("testing_procedure", models.TextField(blank=True, null=True)),
                (
                    "common_failures",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "sufficient_techniques",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("keywords", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "WcagSuccessCriteria",
                "db_table": "wcag_success_criteria",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AbTests",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("type", models.TextField()),
                ("status", models.TextField(default="draft")),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "AbTests",
                "db_table": "ab_tests",
            },
        ),
        migrations.CreateModel(
            name="AccessibilityTestSuites",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_test_suites_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "AccessibilityTestSuites",
                "db_table": "accessibility_test_suites",
            },
        ),
        migrations.CreateModel(
            name="AiSafetyFilters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input", models.TextField()),
                ("output", models.TextField(blank=True, null=True)),
                ("flagged", models.BooleanField(default=False)),
                (
                    "flagged_categories",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "confidence_scores",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("action", models.TextField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_safety_filters_message_set",
                        to="ai_core.chatmessages",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_safety_filters_session_set",
                        to="ai_core.chatsessions",
                    ),
                ),
            ],
            options={
                "verbose_name": "AiSafetyFilters",
                "db_table": "ai_safety_filters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MlPredictions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_predictions_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "MlPredictions",
                "db_table": "ml_predictions",
            },
        ),
        migrations.CreateModel(
            name="ModelMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_metadata_organization_set",
                        to="auth_core.organizations",
                    ),
                ),
            ],
            options={
                "verbose_name": "ModelMetadata",
                "db_table": "model_metadata",
            },
        ),
    ]
